### ISSUE TITLE
Source reports misleading

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#1735]
**What we are after**:
Provide users with a complete picture of a committees filings from the district profile page. https://www.fec.gov/data/elections/house/AZ/08/2018/

**Current state**:
The `view` link in the source reports column does not include late filed electronic filings. This is a problem because the current presentation can mislead users about what reports have been filed. 

**Screenshots**:

Current report display
https://www.fec.gov/data/reports/house-senate/?is_amended=false&data_type=processed&committee_id=C00649897&cycle=2018
![image](https://user-images.githubusercontent.com/11817734/35702755-f18ffada-0767-11e8-81c4-b40261076d58.png)

Preferred display of reports and statements 
https://www.fec.gov/data/committee/C00649897/?cycle=2018&tab=filings
![image](https://user-images.githubusercontent.com/11817734/35702896-5ecf4eca-0768-11e8-8379-bd1f360a7330.png)

**Related issue**:
https://github.com/18F/fec-cms/issues/1470 The current solution for #1470 might not resolve some of the confusion around the data elements on the district profile page. The coverage end date applies to the financial information displayed but not necessarily to the reports files by the committee. In the example above, if we had the “coverage ending” language live in production, it doesn’t help the user understand that Hiral for Congress has filed its year-end report. 

**Completion criteria**:
- [ ] as a temporary fix change the link "view source reports" link from `/data/reports/......./` to `data/committee/Cxxxxxxxx/?cycle=2018&tab=filings` for all three (House & Senate, PAC & party and presidential) sets pages.
- [ ] if there is more than one committee chose the PCC
- [ ] might need to reconsider #1470

@JonellaCulmer

**Comment by johnnyporkchops** [comment]
Tried to make a first pas at this here:
https://github.com/18F/fec-cms/pull/1701

**Comment by JonellaCulmer** [comment]
@PaulClark2 For clarity, at what point are the figures on the district profile page table updated to reflect what's submitted in reports (i.e. the Total receipts and Total disbursement columns)?
Is it once reports are processed?

I was looking back through #1372, the research/design discussion, so as not to discount the motivation for #1470. We still need an at-a-glance way to explain which reports contribute to the figures listed on the table, but also to account for filings submitted after the 7:30 cutoff. So a slight modification to the language, as well as the redirect to committee pages, may be sufficient in the interim. 

Also, we need a null state for committees whose numbers say $0.00. My understanding is that it would say $0.00 if they have filed $0.00, have yet to submit any reports, or if their information hasn't been processed yet. If I'm mistaken, or forgot any other situations, please let me know.

First stab: cc: @AmyKort 
- Processed data through 09/30/2017 | View all
- Processed through: October Quarterly | View all

Null state:
- No processed data

**Comment by jenniferthibault** [comment]
⚠️ Long read ahead! We worked through a great discussion of the possible approaches to fixing this this afternoon in design pairing. Recapping here:
____

## A user scenario
A reporter is researching a House district election. From the [district election page](https://www.fec.gov/data/elections/house/AZ/08/2018/), they click the "View" source reports link highlighted below

![screen shot 2018-02-02 at 5 53 09 pm](https://user-images.githubusercontent.com/11636908/35758462-2e8b2f06-0842-11e8-940e-1a665036c5c0.png)

This brings them to the House and Senate committee reports data page for that candidate's principal committee, showing the following results:
![screen shot 2018-02-02 at 5 58 17 pm](https://user-images.githubusercontent.com/11636908/35758567-b501097a-0842-11e8-9fe7-108692286c82.png)

The committee's Year-end Report is not included in this list (where the reporter expected to find it if it had been filed) because the committee filed that report after 7pm ET—the nightly update processing deadline.

Usually, this report would have been available in the "Raw" data view, available in the first toggle on the filter list. However,
- At this time, the raw data toggle on this data table is broken, and incorrectly returns a list of all filings, for everyone
- We do not know if the reporter attempts to look for the raw filing here (if it had been functioning), or not

This presents a confusing scenario where, not knowing where or how to cross-check, someone could conclude that the committee had not filed their Year-end Report, when they actually had. Yet we don't know if the user attempts to find the info in the right place, and was presented with broken functionality or not.

_____

## Problem solving recapped from today's discussion

**Option 1: Changing the destination of the source reports link**
The first possible solution, started above in a PR above, is to link to the principal committee's profile page, which shows two tables of raw and processed filings in one place. However the tables on this page do not surface the total financials as columns in the table—the user has to click into the filings to view more to get that information. 

In design pairing, we discussed that while this brings you to a full list of raw & processed filings, it doesn't fill the need for quick financial summary information associated with those filings.


**Option 2: Repair and improve the existing reports data table interface**
Using what we know about the user scenario, make some immediate repairs to the broken Raw data toggle. Make immediate improvements to the Raw/processed toggle copy, and identify if there are easy design improvements to the visual interface to make this information more noticeable. Then, take a more detailed look at making new/pending filings more noticeable, with deeper interface iterations.

This was the route the group favored pursuing, and we broke down next steps with assignments.

## Next steps

**Immediate:**
- [ ] Hold off on proposed solution to redirect folks to committee profiles. Close [PR #2901](https://github.com/18F/openFEC/pull/2901)
- [ ] Fix the raw button bug: in PR https://github.com/18F/openFEC/pull/2903 
- [ ] Look at language under raw/processed filing toggle - @AmyKort & @llienfec 
- [ ] Identify if there are easy design wins to existing interface, then prioritize for time & effort - @JonellaCulmer 
- [ ] Review language about adding coverage ending date to see if it's accurate and thorough #1470 - @AmyKort & @llienfec 

**Following that:**
- [ ] Pursue more elegant solution that improves existing interface. Make new issue for this work - @jenniferthibault
- [x] Provide more information in the press section around raw/processed filings: Make a new issue for this work in the backlog - @llienfec : https://github.com/18F/fec-cms/issues/1740
