### ISSUE TITLE
Fix Database Migrations for Wagtail 2.0

### ISSUE THREAD

**Issue by annalee** [fecgov/fec-cms#2040]
This issue is one of two split off from #2011 . 

### Goal:

When working on a branch with Wagtail upgraded to 2.0, migrations will fail against a "clean" database. Since test suites always start with a clean database, this is preventing the tests from running. Our goal is to fix our migrations so that they run properly with Wagtail 2.0, thus preventing the test suite and new developer environments from breaking.

### Completion Criteria:

When we run the tests on a branch with Wagtail upgraded to 2.0, the test suite successfully runs (and passes).

### Tasks:

- [x] Determine whether the problem is the order in which tests are running (it is not)
- [x] Diagnose the root cause of the issue (we believe it's a problem with the actual models; either a circular dependency or wagtail's renaming script missing something)
- [x] Write a patch that will fix the issue
- [x] Fix or eliminate any currently broken tests
