### ISSUE TITLE
Test Wagtail 2.0 upgrade by 8/9 before deploy to prod on 8/14

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2220]
The new wagtail 2.0 is now on the development environment. Please make sure that it is tested thoroughly by **Thursday 8/9/2018**, this will give us time to address any critical issues. Deploy to production will be on **8/14/2018**. Any problems from the upgrade, please note within this ticket.

** **Please only do wagtail testing within our development environment only.**

### Things to check
- [x] all templates working     

  - [x] About landing page **(Pat)**
  - [x] Alert for emergency use only **(Pat)**
  - [x] Legal resources landing page (hard coded) **(Pat)**
  - [x] Home page (hard coded) **(Pat)**
  - [x] Services landing page (hard coded) **(Pat)**

  - [x] Home page banner announcement **([Dorothy](https://github.com/fecgov/fec-cms/issues/2220#issuecomment-408898556))**
  - [x] Record page **([Dorothy](https://github.com/fecgov/fec-cms/issues/2220#issuecomment-409323542))**
  - [x] Tips for treasurers page **([Dorothy](https://github.com/fecgov/fec-cms/issues/2220#issuecomment-408908848))**
  - [x] Press release page **(Lauren)**
 
  - [x] Custom page **([Dorothy](https://github.com/fecgov/fec-cms/issues/2220#issuecomment-408896976) and Lauren)**
  - [x] Resource page **([Dorothy](https://github.com/fecgov/fec-cms/issues/2220#issuecomment-409648478) and Lauren)**

  - [x] Reporting example page **(Lauren)**
  - [x] Reports landing page **(Lauren)**
  - [ ] Meeting page **(- [  ] Dorothy,  - [ X ] John)**
  - [x] Press landing page **(Lauren)**

  - [x] Collection page **(Jonella)**
  - [x] Commissioner page **(Jonella)**
  - [x] Digest page **(Jonella)**
  - [x] Document feed page **(Jonella)**
  - [x] Document page **(Jonella)**
- [x] Spot check places in templates where there is an HTML block to make sure it is still rendering correctly.
- [x] Try adding an HTML block to the template to see if you can add it
- [x] as much as possible, all fields are marked not required or required as needed (don't use feature environment to compare)
- [x] check that frequently-used features are present
- [x] use fix list from prior issue (https://github.com/fecgov/fec-cms/issues/1973, https://github.com/fecgov/fec-cms/issues/2024, and https://github.com/fecgov/fec-cms/issues/1994) to make sure all fixes were made

**Comment by patphongs** [comment]
Two issues discussed in design sync:

- Anchor font size is changed and makes it a link. We need to make it more seamless so that you can make an anchor on any element. Also talked about adding an additional pop-up that would give you the link within the anchor pop-up to show you the anchor link created.

- `P` block button is not in editor. Should be a configuration: https://github.com/springload/draftail#built-in-formats

**Comment by dorothyyeager** [comment]
**Custom page template** testing results for Dorothy: 
-Dealbreakers with glossary and mandatory v. optional options resolved.
**Issues noted**
- [ ] Heading option in body shrunk text. Was unable to apply a heading size.
- [ ] Could not indent in the numbered list. Would have to do work-around with html block (which did work)
- [ ] Unable to indent in the bulleted list. Would have to do work-around with html block (which did work)
-Weird not to see the link text when making external link (but it still worked).
- [ ] The embedded video link still creates a huge (not wanted) block of white space. Will need to do work-around with html block  (which did work)
- Unable to tell if image block worked.
- Internal and External buttons worked but there's no line space after them. This looked crowded if they were put next to each other or to other features.

**Comment by dorothyyeager** [comment]
**Home page banner** working great. (It will go inactive on 7/31, so will doublecheck that it did.

**Comment by dorothyyeager** [comment]
**Tips for treasurers page** template testing results
Dealbreaker with glossary resolved. Overall looks good!
**Issues noted**
- [ ] An internal link copied/pasted as an external link and link text doesn't show when you view button (not a dealbreaker but a little weird).
- [ ] Could not indent bulleted list unless I used html block.
- [ ] Embedded video link button created huge white space. HTML block workaround works but is not responsive unless we add code. See #2212.
- Horizontal line did not show up. Not needed for this template though.

**Comment by dorothyyeager** [comment]
**Record page template** results:

- [ ] Link text does not show up in the link box.
- [ ] Embed video in RTE created that giant white space again. Workaround with HTML block was not mobile-responsive (it probably needs code - see #2212 ).
- [ ] Horizontal line does not render.

Also noted:

- Images don't render in dev, so not sure if it worked.
- This was strange - when I went to insert or delete rows in both normal and custom table, the page went to the top (when I scrolled back down to the table, I was able to do what I wanted).
- Making something into an anchor stripped it of its glossary coding. (Not a dealbreaker but good to know.)

**Comment by JonellaCulmer** [comment]
**Collection page template** results:
- [ ] Embed video, unlikely to be used on this page, creates a giant white space below it
- [ ] Horizontal line does not render

**Comment by dorothyyeager** [comment]
**Resource page template** results

- [ ] Images a problem. Unable to insert an image into the paragraph block either with a separate tool or by using the image insertion icon. There's an image option in the section field, but we need it in paragraph block.
- [ ] Unable to see text in link dialog box
- [ ] Embed video link still with the weird white space. HTML block worked as a workaround but is not mobile-responsive. See #2212 )
- [ ] Citation section still rendered blue even when rest of page breadcrumb was turned red.
- [ ] Internal and external buttons work but need a white space after them or they crowd whatever is next. Here's a screencap
![image](https://user-images.githubusercontent.com/24437369/43536794-7f006ce0-958b-11e8-84d4-36ebb30ecbdc.png)

- [ ] Related pages boxes are rendering blue even if rest of page breadcrumb is red. One related page link I added did not show up at all.
- [ ] If something was in the aside block (thank you for making that optional!), snippet and reporting card were weirdly squeezed. Here's a screencap. This could be resolved by not using "aside" but there might come a time when we wanted to.
![image](https://user-images.githubusercontent.com/24437369/43536768-6dd7e6c8-958b-11e8-8904-edcb41c0ef17.png)

**Comment by patphongs** [comment]
# Pat's testing results

## About landing page

- Within the existing About page, I tested creating a new tab section with Title, Intro, Button, and Related page link, everything was created as expected.

## Alert for emergency use only

- Emergency alert banner works as expected. Testing expiration at noon today, will update to make sure it expires correctly.

![screen shot 2018-08-08 at 11 04 44 am](https://user-images.githubusercontent.com/12799132/43845859-fb384372-9afa-11e8-9c1d-6bc4b5d90ed3.png)

**Minor issue found:**
- The multi field title h2 label in red is cutting off slightly on the second line. There is a fixed 40px height on the `.object>h2` element. This will cause issue on smaller screens as the text will start to cut off. 

![screen shot 2018-08-08 at 10 56 33 am](https://user-images.githubusercontent.com/12799132/43845358-d008fc74-9af9-11e8-8fe9-50236440fa3d.png)

## Legal resources landing page

- Legal landing page looks good visually, no unexpected styling
- Legal news feed is populating and updating as expected
- Performed a legal searching from landing page as well as using the more keyword options, works as expected

## Home page

- Home page looks good visually, no unexpected styling
- News and announcements & Events and deadlines section still populate as expected. Also tested making a change to the title of a record article to make sure that the title of the link changed and it did.

## Services landing page (hard coded) (Pat)

- Services landing page looks good visually, no unexpected styling

**Minor issue found:**
- The Intro section that is on the services landing page template by default is required when there is no text in there to begin with. This would block users from updating the Hero section when needed. I attempted to add text to the Intro section to save and publish the template to see what happens. The Intro text does not appear to be on the page even though it's populated.

**Comment by JonellaCulmer** [comment]
**Commissioner page** test results:
Potential dealbreaker observed:
- [ ] Created an internal link to the Registration and reporting page, only a blank page rendered. Image below: 
<img width="718" alt="screen shot 2018-08-08 at 3 09 43 pm" src="https://user-images.githubusercontent.com/31663028/43859160-e3455b42-9b1d-11e8-9142-e243ab5a486d.png">
------

Other, non-dealbreaker issues, observed: 
- [ ] Embed video creates a giant white space below it
- [ ] Horizontal line does not render

**Comment by JonellaCulmer** [comment]
**Digest page** test results:
Observed no dealbreakers, other observed issues:
- [ ] This page does not have a wysiwyg button for the H5 tag
- [ ] Horizontal line does not render
- [ ] Embed video creates giant white space below it.

**Comment by JonellaCulmer** [comment]
**Document feed page** test results:
Dealbreakers observed:
- [ ] The documents associated with a feed or collection, did not populate. While I could select specific categories from the dropdown, no documents appeared.
<img width="909" alt="screen shot 2018-08-08 at 4 10 33 pm" src="https://user-images.githubusercontent.com/31663028/43861698-9ccd6d82-9b25-11e8-95d7-4001cb4969c9.png">

Other non-dealbreaker issues observed:
- [ ] This page does not have a wysiwyg button for the H5 tag
- [ ] Horizontal line does not render
- [ ] Embed video creates giant white space below it.
- [ ] Could not insert a photo. The pop-up box would not allow me to insert the image, unresponsive "submit" button
<img width="1025" alt="screen shot 2018-08-08 at 4 07 10 pm" src="https://user-images.githubusercontent.com/31663028/43861806-ece240cc-9b25-11e8-8e11-8567a3ee6343.png">
<img width="1015" alt="screen shot 2018-08-08 at 4 07 16 pm" src="https://user-images.githubusercontent.com/31663028/43861802-e7d7ed48-9b25-11e8-9b18-15576ee98aaa.png">

**Comment by JonellaCulmer** [comment]
**Document page** test results:
No dealbreaker issues observed, other issues observed:
- [ ] This page does not have a wysiwyg button for the H5 tag
- [ ] Horizontal line does not render
- [ ] Embed video creates giant white space below it.
- [ ] Could not insert a photo. The pop-up box would not allow me to insert the image, unresponsive "submit" button. See images in previous comment.

**Comment by llienfec** [comment]
### Reports landing page
Looks good!

**Comment by llienfec** [comment]
The only remaining items were from design sync discussion and logged by @patphongs above:

- Anchor font size is changed and makes it a link. We need to make it more seamless so that you can make an anchor on any element. Also talked about adding an additional pop-up that would give you the link within the anchor pop-up to show you the anchor link created.
- P block button is not in editor. Should be a configuration: https://github.com/springload/draftail#built-in-formats

**Comment by patphongs** [comment]
@llienfec @dorothyyeager @JonellaCulmer Since testing has been completed, I am closing this issue. If there's anything here that needs to be pulled out into a separate issue, please feel free to do so. I know a much wanted feature is to have copy and paste work in the rich text editor which @apburnes found out if we upgrade our wagtail to v 2.2.1, that will work! But we've got to do some additional testing for that upgrade. Will open up a separate ticket for that when it's pushed to our feature space.
