### ISSUE TITLE
Create Edit HTML React Component for Draftail Editor

### ISSUE THREAD

**Issue by apburnes** [fecgov/fec-cms#2234]
This is the second part of #1971 

Since the first part has been closed and merged by #2190, this issue will follow the second part which is creating the HTML React component editor

**Comment by apburnes** [comment]
**TODO**

- [ ] Register wagtail rich text editor hook for html editor
- [ ] Create module component to display editor as html
- [ ] Create submit action to save edited html to wagtail rich text editor
- [ ] Add component to tests

**Comment by apburnes** [comment]
Do to the technical debt, [discouraged by wagtail maintainers](https://github.com/springload/draftail/issues/156), and the HTML block option, this issue is being closed in favor of building type specific tools for the editor.
