### ISSUE TITLE
Upgrade to latest version of React v16.x

### ISSUE THREAD

**Issue by apburnes** [fecgov/fec-cms#2291]
Upgrade React to newest version of v16.4.x from v15.5.x to support new features added in Wagtail's Draftail editor and avoid using methods being deprecated in React and dependencies.

**Areas Effected**

- `js/legal` - The legal app which effects all routes under https://www.fec.gov/legal-resources/
- `js/draftail` - The Draftail plugins used in the Wagtail paragraph editor
- JS React tests

**ToDo**

- [x] Upgrade `react`, `react-dom`, and any other dependencies
- [x] Upgrade `enzyme` and `karma` JS testing dependencies
- [x] Check functionality on the Wagtail Draftail Editor and functionality of https://www.fec.gov/legal-resources/
