### ISSUE TITLE
Test Wagtail v2.2.1 upgrade due on 9/6/2018

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2305]
Wagtail 2.2.1 is now on the feature environment (https://fec-feature-cms.app.cloud.gov/). Please make sure that it is tested thoroughly by **Thursday 9/6/2018**, this will give us time to address any critical issues. Deploy to production will be on **9/11/2018**. Any problems from the upgrade, please note within this ticket.

** **Please only do wagtail testing within our feature environment only.**

### Things to check
- [ ] all templates working     
  - [x] Alert for emergency use only **(Pat)**
  - [x] Home page banner announcement **(Dorothy)**
  - [x] Record page **(Dorothy)** - See [comment](https://github.com/fecgov/fec-cms/issues/2305#issuecomment-417687039) for minor issues.
  - [x] Tips for treasurers page **(Dorothy)** - See [comment](https://github.com/fecgov/fec-cms/issues/2305#issuecomment-417714732).
  - [x] Press release page **(Lauren)**
  - [x] Custom page **(Dorothy)** - See [commen](https://github.com/fecgov/fec-cms/issues/2305#issuecomment-418712789)t
  - [x] Resource page **(Dorothy and Lauren)** - [Dorothy's comments](https://github.com/fecgov/fec-cms/issues/2305#issuecomment-418765805)
  - [x] Reporting example page **(Lauren)**
  - [x] Reports landing page **(Lauren)** - HAS ISSUES
  - [x] Meeting page **(John)**
  - [x] Collection page **(Jonella)**
  - [x] Commissioner page **(Jonella)**
  - [x] Digest page **(Jonella)**
  - [x] Document feed page **(Jonella)**
  - [x] Document page **(Jonella)**
- [x] Test copy and paste into rich text editor blocks to make sure it retains links, glossary items, anchor links correctly
- [ ] All fields are marked not required or required as needed
- [ ] use fix list from prior issues (https://github.com/fecgov/fec-cms/issues/1973, https://github.com/fecgov/fec-cms/issues/2024, and https://github.com/fecgov/fec-cms/issues/1994), https://github.com/fecgov/fec-cms/issues/2220 to make sure all fixes were made

**Comment by dorothyyeager** [comment]
Home page banner checks out great!

**Comment by dorothyyeager** [comment]
**Record page template test**
No major issues or dealbreakers found. Minor issues:
- [ ] Cannot indent bullets or numbered lists. Would use html block as work around..
- [ ] Anchor links did not work. Since we actively discourage the use of footnotes in Record articles, this actually works for us but might be something to test in the other content templates.
- [ ]

**Comment by dorothyyeager** [comment]
Tips for Treasurers template test
- [ ] When I copied/pasted from another Wagtail page in edit mode, the links did not transfer but the glossary entry did. When I copied/pasted from the web itself, the links transferred but the glossary entry didn't.

Minor issue:
- [ ] Cannot indent bullets or numbered lists. Would use html block as work around. These lists are very rarely used for tips.

**Comment by llienfec** [comment]
### Reports landing page  (!!!)
- [ ] Not able to preview, save or publish page

### Resource template
Buttons and legal citations section are the wrong color (should be red). Known issue.

### Reporting examples template 
Looks good.  Cutting and pasting links/glossary terms to another section worked!

### Press release template
Looks good.  Cutting and pasting links worked.  Custom table looks good.

**Comment by dorothyyeager** [comment]
**Custom page template.** 
Mostly minor issues, with one exception.

- [ ] Heading block resulted in really small text. We are not using this block much if at all.
- [ ] Cutting/pasting from a website stripped all links and glossary codes. (It worked fine between the blocks or between wagtail pages.)
- [ ] Can not indent the numbered list.

**Comment by llienfec** [comment]
Oh, above when I said cutting and pasting worked, I meant from one block in Wagtail to another block in Wagtail.

**Comment by johnnyporkchops** [comment]
Meeting page template works

**Comment by dorothyyeager** [comment]
Resource template
 - [ ] Buttons and legal citations section are the wrong color (should be red if a H4CC page). I was able to toggle the breadcrumb color.
- [ ] Still have the small font in indented lists in the intro section. Known issue, not a dealbreaker.
- [ ] An image placed as a separate section worked, but the anchor link on the left side menu did not work. This is a feature we might want to incorporate in future outreach pages, so definitely would want to fix this. Not sure it's quite dealbreaker level though.
- [ ] Copying/pasting worked and links were preserved whether copied/pasted from web or wagtail. Glossary codes copied/pasted fine between wagtail and between text blocks, but did not hold up if pasted from web.
- [ ] Testing an anchor link caused a crash in RTE editor.

**Comment by patphongs** [comment]
Emergency alert banner worked. Tested by creating a new banner and scheduled it to publish and unpublish.

**Comment by patphongs** [comment]
> Not able to preview, save or publish page

@llienfec I took a look at this and it appears that we can't create additional reports landing pages, however, you are able to modify the existing one and publish it. We generally only need one of these pages and we hook up additional document feeds to it when needed. So I think it would be ok if this bug remained for now, even after upgrade.

**Comment by JonellaCulmer** [comment]
**Digest page template:** No dealbreakers
- [ ] Does not retain copied glossary link from the website, but copies fine from within wagtail
- [ ] Dividing line does not appear, same as with everywhere else

**Document feed template:** No dealbreakers
- [ ] Does not retain copied glossary link from the website, but copies fine from within wagtail
- [ ] Dividing line does not appear, same as with everywhere else

**Document page template:** No dealbreakers
- [ ] Does not retain copied glossary link from the website, but copies fine from within wagtail
- [ ] Dividing line does not appear, same as with everywhere else

**Comment by patphongs** [comment]
Testing for wagtail 2.2.1 is now complete. There are no major dealbreakers noted in this ticket and any outstanding issues have been transferred to this ticket: https://github.com/fecgov/fec-cms/issues/2337
