### ISSUE TITLE
Refactor and bug fix candidate profile page logic

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2349]
The following PR https://github.com/fecgov/fec-cms/pull/2320 helped to refactor candidate view, fix 404's for future cycle candidates without committees, simplify 2-year select macro and use it for the candidate raising/spending pages.

Using that PR as a conceptual launching point, this is the *completion criteria:*
- [ ] Write tests for bugs before development starts
- [ ] Take a look at the candidate profile page testing issue and fix problems specified in that issue: https://github.com/fecgov/fec-cms/issues/2344
- [ ] Take a look at this issue for examples of future candidates that 404: https://github.com/fecgov/fec-cms/issues/2294
- [ ] Take a look at bugs found for terminated committee pages: https://github.com/fecgov/fec-cms/issues/2343
- [ ] Work with other devs to make sure you can push up the PR to our feature space for testing
- [ ] Once bugs have been fixed, create a PR and a new testing issue to test the candidate profile pages

**Comment by patphongs** [comment]
We should check future election years business logic and make sure we refactor code appropriately. For future election years we only have data up to cycle 2018. cc @PaulClark2 @AmyKort

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/2463
