### ISSUE TITLE
Update social media meta data descriptions

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2423]
What do we want: Update our social media meta descriptions.

Why do we want it: Our social media descriptions state "The new fec.gov makes it easier than ever to find what you need to know about the federal campaign finance process. Explore legal resources, campaign finance data, help for candidates and committees, and more."

This is great, but it's out of date. Users coming to our site no longer need to be oriented to the changes from the classic site. We've also heard from folks that the description is too long. Let's draft a new description.

Completion Criteria:
 - [ ]  draft new language
 - [ ]  run past Info and Press
 - [ ] make implementation ticket

**Comment by AmyKort** [comment]
How about just: Find what you need to know about the federal campaign finance process. Explore legal resources, campaign finance data, help for candidates and committees, and more."

**Comment by lbeaufort** [comment]
We can update the meta descriptions in the [`get_meta_description`](https://github.com/fecgov/fec-cms/blob/develop/fec/home/templatetags/filters.py#L115) function, and preview them with https://megatags.co/validators/

**Comment by lbeaufort** [comment]
@AmyKort it looks like the meta tags are set up to preview differently depending on the section of the site (below). Should the "meta" be the same for all pages?

```
    if content_section == 'help':
        return 'Learn how individuals and groups can be active in federal elections. The new fec.gov organizes reporting and compliance guidance by the type of committee you’re researching, so you can find what you need right away.'
    if content_section == 'legal':
        return 'Clarify campaign finance legal requirements on the new fec.gov. Search across advisory opinions, Matters Under Review, statutes, and regulations all at once, with search results designed to help you find what you need quickly.'
    else:
        return 'The new fec.gov makes it easier than ever to find what you need to know about the federal campaign finance process. Explore legal resources, campaign finance data, help for candidates and committees, and more.'
```

**Comment by AmyKort** [comment]
I would say yes. One of the concerns raised about the meta tags was that they are very long, and it might be better to go with the shorter version for all pages. What do you think @JonellaCulmer ?

**Comment by JonellaCulmer** [comment]
I'm leaning towards yes, @AmyKort  Maybe there's a compromise? Specific meta tags for each section that play off the approved version you have above. 

Such as: (super not good language about to happen)
- Find the legal resources you need to know to learn more about the federal campaign finance process.
- Find the data you need to learn more about the federal campaign finance process...
- Learn what individuals and groups need to know about the federal campaign finance process.

**Comment by AmyKort** [comment]
Too short?

Find federal campaign finance legal resources 
Explore federal campaign finance data 
Find information and resources for federal candidates and committees

tagging @llienfec @dorothyyeager @rhoughfec  @JonellaCulmer

**Comment by dorothyyeager** [comment]
I like the first two, @AmyKort . For the third, how about
"Find compliance information and resources for federal candidates, political committees and other individuals and groups"
(I'm not wed to this.)

**Comment by dorothyyeager** [comment]
Just quickly conferred with @AmyKort. We'll use one tag throughout, with the language Info and Press liked:

Find what you need to know about the federal campaign finance process. Explore legal resources, campaign finance data, help for candidates and committees, and more.
