### ISSUE TITLE
Convert the E&J word tables into html blocks for Wagtail, part 1

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2496]
**User story**
As an internal stakeholder or outside legal consultant, I need to see the explanation and justification for Commission regulations to do proper legal analysis of them.

**Background:** #2202, #2325, #2392, #2445, #2477 

**Work plan** 
In the previous issues above, we updated E&J links and made word tables for them. Now we're ready to tackle converting those word tables into html blocks, which will go into new Wagtail pages. We'll do this in two-week blocks of work.

**To do this sprint:**
- [x] Convert the word tables for Parts 1-8 into html blocks.

**Future sprints**
Convert the word tables for these parts:
- [ ] Parts 100-109 - many tables - we will need to split out the parts 100-116 regs more since we don't want more than 6 tables per page.
- [ ] Parts 110 -116 - many tables
- [ ] Parts 200-203 - only three tables
- [ ] Parts 300 and 400 - not many tables
- [ ] Parts 9001-9007/9012 - many tables
- [ ] Parts 9008 - not many tables
- [ ] Part 9031-9039 -many tables

**Comment by dorothyyeager** [comment]
Work on Parts 1-8 conversion is done and a draft page is set up in Wagtail.

One lesson learned: Because these pages use the resource page template, we should limit the number of sections/tables to 7 per page. 8 is the max and it worked but not ideally. Will keep this in mind as we make future pages.

Going to send this draft page for content team review before closing issue, to see if there are any additional concerns.

**Comment by dorothyyeager** [comment]
Have heard no concerns, so we'll close this issue and move on to Part 100 tables in #2532 .
