### ISSUE TITLE
Convert E&J Tables into HTML blocks & create Wagtail pages - Parts 100 and 101/102

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2532]
**User story**
As an internal stakeholder or outside legal consultant, I need to see the explanation and justification for Commission regulations to do proper legal analysis of them.

**Background:** #2202, #2325, #2392, #2445, #2477

**Work plan**
In the previous issues above, we updated E&J links and made word tables for them. Now we're ready to tackle converting those word tables into html blocks, which will go into new Wagtail pages. We'll do this in two-week blocks of work. We did parts 1-8 in #2496 . With two specialists from Info willing to do the legwork of converting the word tables, we'll be able to make two pages at a time. I'll create the pages, and the specialists will convert the word tables and insert the html code.

**To do this sprint:**
- [x] Make resource template pages for Parts 100 and 101/102 of the regs (Part 100  is a huge Part that has six tables so it will need its own page - child page of E&Js) - Dorothy
- [x] Convert word tables for Part 100 into html blocks and insert as sections on new page. - Zainab
- [x] Convert word tables for Parts 101 and 102 into html blocks and insert as sections on new page. - Paul

**Comment by dorothyyeager** [comment]
I made the resource pages that Paul and Zainab will use. Because Part 101 is short, we've added part 102 so that we can use the resource template. I'm meeting with them today to explain the process they'll follow.

**Comment by dorothyyeager** [comment]
Paul has completed his portion, so will create a new ticket for each new portion that he'll work on. Next up is Part 103 and 104.

**Comment by dorothyyeager** [comment]
Zainab has finished her portion too. Their next ticket will be #2553. 

I'll review everything tomorrow, add SEO and then close this ticket. For now will move back to Assigned tickets.

**Comment by dorothyyeager** [comment]
Change of plans: with everything going so smoothly on Zainab and Paul's end, we're going to close this ticket, as initial work is completed, and open one more ticket for all E&J work for the rest of the sprint.  The SEO and quality control portion for me will be worked into that ticket too.
