### ISSUE TITLE
Mock-up nationwide campaign finance maps

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2541]
**User story:** So that users can have a quick, high-level understanding of campaign finance activity across the country, we should provide nationwide campaign finance maps.

### Raising by House/Senate/Presidential by state
<img width="730" alt="screen shot 2018-12-20 at 10 27 26 am" src="https://user-images.githubusercontent.com/31663028/50296076-99bcff00-0447-11e9-85e5-0f74d44ff4de.png">

### Spending by House/Senate/Presidential by state
<img width="581" alt="screen shot 2018-12-20 at 11 07 58 am" src="https://user-images.githubusercontent.com/31663028/50296049-8d38a680-0447-11e9-83f0-a966ebead969.png">

- [x] Update mockups for H/S/P
- [x] Update mockups to include overall totals
- [x] Decide on placement of campaign finance maps on "Explore all data" and fec.gov homepage
- [x] Content review of language for data landing and homepage
- [X] Make an implementation ticket 
- [x] Update mockup to include the ability to change date range. (Is this 2-year period or whole election cycle? We do full election cycle totals for the election profile pages)

**Comment by lbeaufort** [comment]
@AmyKort @JonellaCulmer we had also discussed replacing this icon with a map icon: 
<img width="317" alt="screen shot 2018-11-27 at 4 37 43 pm" src="https://user-images.githubusercontent.com/31420082/49113208-ea837280-f262-11e8-9702-6e840196cdeb.png">

**Comment by JonellaCulmer** [comment]
Based on a discussion regarding the placement of new and old map visualizations on the data landing page and homepage, we have a solid direction for what we need to accomplish next. 

To firm up the below mock-ups, we need a content review on the language in sections highlighted in pink text and pink boxes. Specifically, we need a content review on the headers, description text and button text for the Getting started and new Explore data sections on the homepage. As well as the card text to direct users to the soon-to-be-developed maps on the by-the-numbers pages. 

## Designs
### homepage mock-up
![screen shot 2018-12-04 at 11 41 08 am](https://user-images.githubusercontent.com/31663028/49457826-88be8d80-f7b9-11e8-819d-5dab24d24b1e.png)

### data landing page mock-up
![screen shot 2018-12-04 at 11 40 17 am](https://user-images.githubusercontent.com/31663028/49457759-64fb4780-f7b9-11e8-9a5f-1502c145ddcc.png)

### Next steps:

**Phase One**
- [ ] Content review for homepage mock up @dorothyyeager @AmyKort (and Kathy)
- [ ] Content review for data landing page mock up @dorothyyeager @AmyKort (and Kathy)
- [ ] Create follow-up ticket to implement homepage mock up 
**Phase Two**
- [ ] Create follow-up ticket to develop maps (feature branch work here: https://github.com/fecgov/fec-cms/issues/2542) 
- [ ] Create follow-up ticket to implement data landing page mock up and new maps
**Phase Three**
- [ ] Create follow-up ticket to mock-up homepage changes for redesign of "Getting started" section (phase three)

**Comment by dorothyyeager** [comment]
Tagging @kathycarothers :)

**Comment by dorothyyeager** [comment]
I'm good with the data landing pages. Have some thoughts and questions on the home page mockup that we can all talk through in Design Sync.

**Comment by lbeaufort** [comment]
@JonellaCulmer Based on our discussions, I'm reopening to add a way to change date range and adding a completion criteria item.

**Comment by lbeaufort** [comment]
@JonellaCulmer: Also based on our discussions and after checking with @AmyKort and @jwchumley, these maps seem to make the most sense to show **full election totals** because we're talking about elections.

Also, did you want to design the interaction with the map, when the user clicks on or mouses over a state? Here's what happens with the state breakdown maps we have so far:
<img width="368" alt="screen shot 2018-12-14 at 10 34 53 am" src="https://user-images.githubusercontent.com/31420082/50012180-f6be3e00-ff8b-11e8-8b65-c68bb06875f3.png">

**Comment by JonellaCulmer** [comment]
Mockups have been updated based on previous conversations and user testing. Updated mockup in original comment.
