### ISSUE TITLE
Create the rest of the E&J citation index pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2555]
**User story**
As an internal stakeholder or outside legal consultant, I need to see the explanation and justification for Commission regulations to do proper legal analysis of them.

**Background:** #2202, #2325, #2392, #2445, #2477, #2496, #2532,  #2553 

In the previous issues above, we updated E&J links and made word tables for them. We also began creating Wagtail pages, while the specialists converted the word tables and inserted the html code into these new pages.

**Work plan for sprint** 
We're going like gangbusters, so the plan is to create the rest of the pages and finish inserting the code into them. We'll try to get as far as we can with all the parts of FEC regulations and then make a new ticket for the next sprint for any remaining work.

**Completion criteria**
- [ ] Finish initial creation of the resource pages (Dorothy)
- [ ] Paul and Zainab finish converting word tables and inserting the code into the resource pages
- [ ] Dorothy reviews the pages, inserts SEO and does quality checks on them.

**Comment by dorothyyeager** [comment]
Initial pages are created. Paul and Zainab are making quick work of inserting the tables.

**Comment by dorothyyeager** [comment]
We have published the various citation index pages. The next step is to link them in the "Citation index intro page" which will become the page we link from the E&Js. This work is underway in #2569 and we're ready to close this issue.
