### ISSUE TITLE
Data/Design studio to determine the data needs for nationwide election maps

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2586]
Mock-ups: https://github.com/fecgov/fec-cms/issues/2541

Data/design studio to identify exactly what data is needed from the API (and how we need to be able to filter it) to implement the raising and spending maps.

- [X] Hold meeting on day 2 of PI8 planning with entire team
**Questions to answer:**
- [x] Do the maps only include individual contributions? **Only if it's easier**
- [X] Should the map show full election totals? (2/4/6 year totals vs. 2-year totals) **Yes**, but build it to take `election_full` argument and do both
- [x] Do we filter only active candidates **Yes** (raising/spending breakdown shows inactive committees). We should make sure this works for historical data.
- [X] Should the endpoint include a row with the total for all states? **Yes**
- [X]  Do we have an endpoint with 2020 data? **Not yet** This has no results (maybe because it's 2-year period and not 2020 yet? What about election_full? https://api.open.fec.gov/v1/schedules/schedule_a/by_state/totals/?committee_type=P&sort=cycle&api_key=DEMO_KEY&sort_hide_null=false&page=1&per_page=20&cycle=2020&sort_nulls_last=false&sort_null_only=false
- [X] Should the endpoint have the option to do both full-election and 2-year totals with the `election_full` flag? **Yes**
- [X] Show totals going out as far as the next 3 elections **Yes, but 2020 is MVP** (2020, 2022, 2024)
- [X] Add filter for individuals only? **Only if it's easier**
- [X] How do we link each state to a datatable? What's the datatable we need to use? **Receipts/Disbursements** Especially if we want to follow the 2/4/6 time periods
- [X] Make a ticket to research increasing database power in order to display 4 and 6 year increments of data https://github.com/fecgov/openFEC/issues/3544
- [X] Make a ticket to increase database performance https://github.com/fecgov/openFEC/issues/3543
- [X] Create an implementation issue for the API based on findings https://github.com/fecgov/openFEC/issues/3548
    -  Consider building a layer on top of existing candidate totals endpoint?
     - Make `state_full` a sortable parameter
    - add future totals to /schedule_a/by_state/totals
    - see other checkboxes above
- [x] Make a ticket to add a /schedule_a/by_state/totals/by_party/ endpoint with the same data needs (https://github.com/fecgov/openFEC/issues/3549)

**Comment by patphongs** [comment]
All of the items in this ticket have been completed. Logic notes has been moved to this visualization [document](https://docs.google.com/document/d/1HO5fmFKLNQbgu4CCR-kD_e8oWUaM3P_qrKVwnsGxW7I/edit#heading=h.btz7j9kkwo0t) 🔒 

Closing this issue.

**Comment by qqss88** [comment]
need to check the way how we are dealing with non-standard states aggregation(data from 2018):
PR      206
ZZ      198
NaN     192
GU       48
VI       46
AE       44
AA       23
AP       11
AS        6
MP        3
