### ISSUE TITLE
Tech debt related to @extend rule and structure of current table classes

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2864]
**What were after:** Address mounting tech-debt related to how the existing table classes are structured and fix a side-effect of this problem, created by using `@extend`, which compiles absurdly long CSS selectors. Do this in a way that does not require extensive refactoring of the SCSS and does not require content/press team to refactor any of their html.

**The issues  are:**
1) Adding the commonly used class of `simple-table` to tables created in the `html-block` has little effect because the structure requires classes to be applied on each table element (th, tr, td etc), not just on the table itself. Users did not know to do this.  See lines 1-57 of this file:
https://github.com/fecgov/fec-cms/blob/develop/fec/fec/static/scss/components/_table-styles.scss.  This left CMS users without a clear way forward in migrating table content into html blocks, making it difficult to get the desired front-end result.

2) A while back we used the `@extend` rule in an attempt to apply uniform styles to any table created in the CMS HTML blocks (whether the user applied class(es) to the table in the html or not. By `@extending`  the .`simple-table` class on top level containers like `body-blocks` and `block-html` we have the unintended side-effect of absurdly long compiled selectors that are unreadable and add unnecessary size to the compiled CSS. See below screenshot:
![giant-selector](https://user-images.githubusercontent.com/5572856/56783349-6acde580-67b9-11e9-80f4-1dd7a2a2abfb.png)

### Addressing Tech debt:
- [x] We can solve the issue of the absurdly long selectors by  @extending  a new table class called `simple-table-cms`  instead of `simple-table` that would applied to all tables created in CMS `html-blocks` and `body-blocks`. Unlike `simple-table `, this does not have a class on each child element. This still gives us some initial control over default styles for tables added to html blocks without the long selectors. (tested in upcoming branch). Users could still use `simple-table-cms`  and/or other table  classes, like `dense-table`  if they wish.
 
### Tasks:
**Developement Tasks** (addressing tech-debt)
- [x]  Create new simple-table-cms class (this was done in PR https://github.com/fecgov/fec-cms/pull/3227/)
- [ ] In `_richtext.scss`, replace  `@extend .simple-table` with `@extend .simple-table-cms`  for `block-htm`l and `body-block`  
 - [ ] @extend `simple-table-cms` (instead of `simple table`) in `custom-table-block` in _table-styles.scss.
-  [ ] Consider moving the style definitions for the wagtail default table-block from articles.scss to `_rich-text.scss` or `_table-styles.scss` for a more logical organization of table-related styles.

 **Working with Content/UX teams** (addressing tables site-wide)
- [ ] Work with CMS users (content team) to further develop the styles for `simple-table-cms` for use with tables already created in the CMS html-blocks

  -  http://127.0.0.1:8000/campaign-finance-data/independent-expenditures-file-description/ (Make sure everything looks ok and is not negatively visually altered from what is on production
  - http://127.0.0.1:8000/updates/statistical-summary-15-month-campaign-activity-2017-2018-election-cycle/ (Make sure decimal points are still lined up and that the table is not negatively visually altered from what is on production)
  - http://127.0.0.1:8000/ (Use Chrome inspector to inspect simple-table__cell in the Raising/Spending barcharts and make sure that the really long selectors that are currently on production are reduced to a normal length )

- [ ] Make sure classes and style applied to the `table-block` and `custom-table-block` are not effected by this in any way and make adjustments if necessary.  This includes working with press office (Carmen) to make sure the `statistical press releases` look as they should after the refactor.
