### ISSUE TITLE
Testing ticket: Where individual contributions come from

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3146]
**What we're after:**
This is a testing ticket to test Where individual contributions come from and implement any outstanding issues that must be resolved before making this feature live.

### Related issues
- https://github.com/fecgov/fec-cms/issues/2929
- https://github.com/fecgov/fec-cms/issues/3204
- https://github.com/fecgov/fec-cms/pull/3208

### Completion criteria
- [x] hold meeting with testers/devs to identify testing steps
- [x] decide what testing steps are needed to satisfy thorough testing for #2929 
- [ ] document work still needed and determine priority level

**Comment by JonellaCulmer** [comment]
Below is the testing criteria required for the WCCF feature. 

**Where individual contributions come from testing**
Test primarily on stage.

_Feature link on stage:_ https://fec-stage-proxy.app.cloud.gov/data/raising-bythenumbers/#contributions-by-state
_Feature link on dev:_ https://fec-dev-proxy.app.cloud.gov/data/raising-bythenumbers/#contributions-by-state

**Number of testers needed:**
2 testers. 

**Note:**
Cross-site origin error when loading the stage environment. So testers may need to switch between the dev and stage environments to address the error. 

**Business criteria/testing tasks:** 

1. Confirm that a candidate’s available cycles are listed.
2. Confirm that a selected candidate’s latest cycle appears on load of the candidate.
3. Confirm the aggregate total shown for a given candidate is accurate. (1 or 2 candidates in H/S/P across a couple different election time periods (2/4/6 years) should suffice)
4. Confirm dollar figures shown in map view are the same as what is shown in the table. Confirm these dollar figures are accurate. (1 or 2 states per candidate type (H/S/P) across a couple different election time periods (2/4/6 years) should suffice
5. Confirm the error message appears when a candidate, who does not exist is typed in to the search box. Error message: “You entered a candidate name or candidate ID not associated with a registered candidate. Please try again.”
6. Laura: Confirm the methodology is correct.
7. Confirm that the candidate’s information/details are accurate.

**As work is completed [here](https://github.com/fecgov/fec-cms/issues/3203) and [here](https://github.com/fecgov/fec-cms/issues/3204), we will test the following:**

8. Confirm the error message appears when a candidate has no itemized contributions. Error message: “We don't have itemized individual contributions for this candidate for 2015-2020.”
9. Confirm that coverage dates listed per candidate are accurate to the election time period.
10. Confirm that the Browse individual contributions button goes to a filtered view of the individual contributions datatable by candidate’s committees and by applicable election cycles, for a given election year.
11. Confirm that selecting a candidate name and going to the candidate profile page is going to the proper election year. (If viewing Trump in 2020, make sure the candidate profile page defaults to 2020). (1 or 2 candidates in H/S/P across a couple different election time periods (2/4/6 years) should suffice)
12. Confirm that the key correctly shows all applicable colors in the map view.

**Comment by PaulClark2** [comment]
@JonellaCulmer 

#1 
D. Trump - yes displays candidate’s available cycles
N. Pelosi - yes displays candidate’s available cycles
T. Lott - yes displays candidate’s available cycles
S. Thurmond - yes displays candidate’s available cycles
J. Ossoff (House) - no ?? shows 2017; map is white and no state data -- should it show 2018, instead
D. Jones -yes

#2 
D. Trump - yes most recent cycle appears on load
N. Pelosi - yes most recent cycle appears on load
T. Lott - yes most recent cycle appears on load
S. Thurmond - yes most recent cycle appears on load
J. Ossoff - displays 2017 instead of 2018
D. Jones - yes most recent cycle appears on load

#3
P. Buttigieg 2020 president - small discrepancy - not concerned

- Displayed totals match totals from ofec_sched_a_agg_state_vw. 
- Reported total itemized individual contributions (no line 12 data)  ($16,552,974.00) 
- WCCF ($16,548,965)
     -  difference $3,435

A. Ocasio-Cortez 2020 House- ok

- Displayed totals match totals from ofec_sched_a_agg_state_vw. 
- Reported 2020 total itemized individual contributions ($334,401.45) match WCCF ($334,001)

M. McConnell 2020 Senate - PROBLEM 

- WCCF California $446,462 
- ofec_sched_a_agg_state_vw California $143,377
- WCCF total $6,509,434
- ofec_sched_a_agg_state_vw  $3,312,824.70 `
- `select sum(total) from ofec_sched_a_agg_state_vw where cmte_id = 'C00193342'and cycle = 2020;`
- Reported itemized individual contributions $2,470,220.95 but McConnell has $948,860.95 in transfers (Line 12). Assuming most of those transactions are individual contributions that gives us about $3.3 million

 

#4
J. Manchin 2024 Senate - match
R. Santorum 1992 House  - match
B. Barr 2002 House - match

#5 
confirmed

#6 
B. Clinton president 1996 - ok
M. Williamson president 2020 - ok 
K. McCarthy House 2020 - ok
P. Ryan House 2012 - ok
D. Durbin Senate 2008 - ok

**Comment by patphongs** [comment]
Thanks for testing @PaulClark2 !

> J. Ossoff (House) - no ?? shows 2017; map is white and no state data -- should it show 2018, instead
For this problem, I think we have CMS logic to increment the special election year if it's an odd number. 

Looks like we need to add the same logic to this if the array of election years includes an odd number


> M. McConnell 2020 Senate - DATA PROBLEM
> 
> * WCCF California $446,462
> * ofec_sched_a_agg_state_vw California $143,377
> * WCCF total $6,509,434
> * ofec_sched_a_agg_state_vw  $3,312,824.70 `
> * `select sum(total) from ofec_sched_a_agg_state_vw where cmte_id = 'C00193342'and cycle = 2020;`
> * Reported itemized individual contributions $2,470,220.95 but McConnell has $948,860.95 in transfers (Line 12). Assuming most of those transactions are individual contributions that gives us about $3.3 million

This probably needs to be a new ticket to fix this data problem before go live? cc @lbeaufort

**Comment by fec-jli** [comment]
1)
a)CLINTON, HILLARY (presidential) P00003392: yes
CLINTON, HILLARY (senate) S0NY00188 : yes

b)D. Trump (presidential) (P80001571) - : yes 
c)OSSOFF, T. JONATHAN (special house 2017)(H8GA06195) :yes
OSSOFF, T. JONATHAN (senate) S8GA00180: no data ? only can chose 2020?

d)PING, CATHERINE LOUISE “CAT" (House) (H8IN07259) :yes
(2008 and 2012 no data?)

e)GONZALEZ COLON, JENNIFFER (H6PR00082)(Puerto Rico): yes

f) WARREN, ELIZABETH(S2MA00170) (future, 2024 no data): yes
WARREN, ELIZABETH(P00009621) 2020: yes


2)
maybe an issue: not candidate’s latest cycle 
Ex: P00003392 —> select 2018
then search: H8IN07259, still display 2008, should be 2016( the latest cycle)


a)CLINTON, HILLARY (presidential) P00003392: yes,2016
CLINTON, HILLARY (senate) S0NY00188 : yes,2012

b)D. Trump (presidential) (P80001571) - : yes,2020 

c)OSSOFF, T. JONATHAN (special house 2017)(H8GA06195) : yes, 2018
OSSOFF, T. JONATHAN (senate) S8GA00180: yes,2020

d)PING, CATHERINE LOUISE “CAT" (House) (H8IN07259) :yes,2016

e)GONZALEZ COLON, JENNIFFER (H6PR00082)(Puerto Rico): yes 2020

f) WARREN, ELIZABETH(S2MA00170) (future, 2024 no data): yes,2024
WARREN, ELIZABETH(P00009621) 2020: yes 2020

g) RYAN, PAUL D.(H8WI01024)


3) N/A

4)
a)CLINTON, HILLARY (presidential) P00003392: yes,2016
b)WARREN, ELIZABETH(S2MA00170) : yes,2018
c)GONZALEZ COLON, JENNIFFER (H6PR00082)(Puerto Rico): yes 2020

5) confirmed
minor question, Is this ok for red word message not fully cover the Examples text?
<img width="380" alt="Screen Shot 2019-10-01 at 3 56 39 PM" src="https://user-images.githubusercontent.com/24395751/65998114-b53e4700-e468-11e9-98e0-ef2a8cf95c73.png">


6) N/A

7)
RYAN, PAUL D.(H8WI01024): Confirmed
CLINTON, HILLARY (presidential) P00003392: confirmed
WARREN, ELIZABETH(S2MA00170): confirmed

8) Confirmed
9) N/A

10) on Fairfox 
most same as Chrome

**More question for Chrome and Fairfox.** 
1) on Safari: candidate name and election input in one line.
<img width="742" alt="Screen Shot 2019-10-01 at 4 12 18 PM" src="https://user-images.githubusercontent.com/24395751/65998383-2f6ecb80-e469-11e9-93b3-292de2bf067d.png">


on Chrome: election input is  always in second line.
<img width="408" alt="Screen Shot 2019-10-01 at 4 12 12 PM" src="https://user-images.githubusercontent.com/24395751/65998399-3a296080-e469-11e9-9a38-171555835da8.png">


2) The map is under table section on Chrome, is this what we want?  they are side by sice on Fairfox.
<img width="735" alt="Screen Shot 2019-10-01 at 4 14 01 PM" src="https://user-images.githubusercontent.com/24395751/65998445-53321180-e469-11e9-8c6d-b12465d01212.png">


I am testing on Mac.

**Comment by JonellaCulmer** [comment]
Additional work that has come out of this testing:
- [ ] Decouple election year in URL from Where contributions come from https://github.com/fecgov/fec-cms/issues/3231
- [ ] WCCF: Make individual contribution committee api call consistent https://github.com/fecgov/fec-cms/issues/3232

**Comment by patphongs** [comment]
Logged a new testing bug for internet explorer: https://github.com/fecgov/fec-cms/issues/3246

Closing out this ticket as I think everything else has been tested.
