### ISSUE TITLE
Tag Manager implementation

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#3160]
Extending from [#3154](https://github.com/fecgov/fec-cms/pull/3154), a ticket to continue the Tag Manager implementation. This issue may or may not have a PR as the work _could_ happen entirely in the gtm interface and not touch the repo at all.

Progress:
- [x] Add feature flag (done in #3154)
- [x] Wrap current analytics inside the feature flag (done in #3154)
- [x] Create Tag Manager (GTM) container for non-Production (done in #3154)
- [x] Add Production GTM container to pages behind feature flag (done in #3154)
- [x] Add non-Production container to pages as an alternate to the Production container (done in #3154)
- [x] Add `<noscript>` GTM elements to templates (done in #3154)
- [x] Add code to non-Production container to confirm it's loading (done in #3154)
- [x] Confirm proper GA/DAP/GTM elements are loading (done in #3154)
- [x] Comb site to migrate any necessary GA events to GTM data layer
- [x] Confirm successful migration of GA events to GTM
- [x] Confirm GSA DAP is unaffected (all GSA DAP events are still coming through)
- [x] Remove current/then-retired GA implementation and conditionals (#4104 )

#3906 will serve as a kind of PR since this won't be in Git

Next steps in order:
- #3906 Test to make sure that GTM is successfully going into pages, adding GA accounts to pages
- #3972 Duplicate Google Tag Manager to prod 
- #3971 Approve Google Tag Manager on production
- #3973 Deploy Google Tag Manager with env vars
- #3948 Add new events into Google Tag Manager

**Comment by jason-upchurch** [comment]
@rfultz I moved this to PI 13 innovation sprint--please let me know if I can help in any way. Thank you!

**Comment by rfultz** [comment]
Final check is checked, so I'm closing it
