### ISSUE TITLE
Test Wagtail upgrade

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3566]
### Summary

**What we are after:**
_We need to make sure Wagtail works well for internal users who post updates to the website._

Latest update is now on the feature environment (https://fec-feature-cms.app.cloud.gov/). Please make sure that it is tested thoroughly by Thursday 3/5/2020; this will give us time to address any critical issues. Deploy to production will be on 3/10/2020. Any problems from the upgrade, please note within this ticket.

**Please only do wagtail testing within our feature environment only.**

### Related issues

- #2305 (for previous example of testing)
- https://github.com/fecgov/fec-cms/pull/3563 (Upgrade Django/Wagtail packages PR)

### Completion criteria

Ensure that all templates are working. Test copy and paste into rich text editor blocks to make sure it retains links, glossary items, other features correctly. Make comment in this ticket after testing each template (see previous ticket for example).

- [x] Alert for emergency use only  (Dorothy) - Works great.
- [x]  Home page banner announcement  (Dorothy) - Works great.
- [x]  Record page (Dorothy) - See [comment](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-589700365)
- [x] Tips for Treasurers page (Kathy) - Works great. 
- [x]  Press release page (Dorothy) - See [comment](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-589267643).
- [x]  Digest page (Kathy) - See [Kathy's comments](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-589731136)
- [x]  Meeting page (Dorothy) - Works great.
- [x]  Custom page (Dorothy and Kathy) - See [Dorothy's comments](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-589719674)
- [x]  Resource page (Dorothy and Kathy) - See [Kathy's comments](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-589724011) and [Dorothy's comments](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-589733386)
- [x]  Reporting example page (Kathy) See [Kathy's comment](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-589741118)
- [x]  Reports landing page (Front end)
- [x]  Collection page (Dorothy) - See [comment](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-589817622)
- [x]  Commissioner page (Dorothy) - See [comment](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-589799262)
- [x]  Document feed page (Dorothy)  - Works great. We should think about using this template more; it might work for a Policy page.
- [x]  Document page (Dorothy) - Works great
- [x]  Full-width page (Kathy - @djgarr should test this too since he works with this template for dates and deadlines.) Needs fixing - see [comment](https://github.com/fecgov/fec-cms/issues/3566#issuecomment-590933365) by @djgarr about citations not showing up.

### Future work

Open implementation tickets to make fixes as needed.

**Comment by dorothyyeager** [comment]
**Press Release page**
Only two issues observed:
- Known issue with horizontal rule not appearing; not a dealbreaker.
- In the custom table footnote field, unable to superscript the footnote number (html didn't work). There are some footnotes which will use links, so we may want to enable this ability.

**Comment by kathycarothers** [comment]
Tips for Treasurer 
Only one issue observed:

- Only the paragraph option is working from the features to choose from in the Body. The others do not show-up in live form. All functions within the paragraph option are working.  Please see the image below. @dorothyyeager Double-checking with Dorothy to see if these other features are needed. 

![image](https://user-images.githubusercontent.com/32739251/74972913-911bdc00-53f0-11ea-8fa3-4990847faae9.png)

**Comment by kathycarothers** [comment]
**Digest page** 

- I am unable to get the CONTACT section to appear.

**Comment by dorothyyeager** [comment]
> Only the paragraph option is working from the features to choose from in the Body. The others do not show-up in live form. All functions within the paragraph option are working. Please see the image below. @dorothyyeager Double-checking with Dorothy to see if these other features are needed.

We do need those features for the tips pages, but I was able to add them to your test page. (You have to hit publish to see them.)

**Comment by dorothyyeager** [comment]
> **Digest page**
> 
> * I am unable to get the CONTACT section to appear.

@kathycarothers I see it. You might have to refresh cache after hitting publish to see change.

**Comment by kathycarothers** [comment]
Okay perfect. I did hit publish. I think it is slow to come up on my machine today or the cache. Thanks! @dorothyyeager

**Comment by dorothyyeager** [comment]
<b>Record page</b>
Issues noted:

- Known issue with horizontal rule not appearing; not a dealbreaker.
- The ability to do an anchor link did not work. Known issue; not a dealbreaker
- In the custom table footnote field, html does not work. There are some footnotes which will use links, so we may want to enable this ability. **This should get fixed if we are going to offer this field.**

**Comment by dorothyyeager** [comment]
**Custom page** - view test at [https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/testing-custom-page-2-21-2020/](https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/testing-custom-page-2-21-2020/)
Issues noted:

- Known issue with horizontal rule not appearing; not a dealbreaker.
- No option within "body" to insert a "custom" table
- The ability to do an anchor link did not work. Known issue; not a dealbreaker
-  In the sidebar, we do not need the options for tables or images (in fact, we'd probably want to discourage them being offered there) I noticed the option for custom table was available here, so that could be moved instead to the body. I liked that we were given the option for adding contact info, but we also have the "show contact link" so I wonder if that's too much. cc @JonellaCulmer 
- The "Related pages" should show up under the citations block.

**Comment by kathycarothers** [comment]
Resource page - https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/dates-and-deadlines/testing-resource-page-february-2020-reporting/

Issue noted:
The ability to do an anchor link did not work. I believe this is a know issue and not a deal breaker. 
- 

-

**Comment by kathycarothers** [comment]
Digest page - https://fec-feature-cms.app.cloud.gov/updates/test-weekly-digest/

Issues noted:

-  The anchor link is not working. Not a deal-breaker.
- The horizontal line is now showing up either. Not a deal-breaker

**Comment by dorothyyeager** [comment]
**Resource page** https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/testing-resource-page-template-2-21-2020/

- Same issues as Kathy's comment above
- When loading the Commissioner snippet, it didn't load the 2020 version of the Commission (not sure if this relates to this being done on feature or not).
- The padding we've built in for various features doesn't seem to be present for things like cards and images.  They're all smushed together.
![image](https://user-images.githubusercontent.com/24437369/75053238-e9a9b280-549e-11ea-95c6-78dd69ee910d.png)

**Comment by kathycarothers** [comment]
Example page: https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/candidate-taking-receipts/test-how-reports-receipts/

Issues noted:

- The anchor link is not working. Not a deal-breaker.
- The horizontal line is not showing up either. Not a deal-breaker

**Comment by dorothyyeager** [comment]
**Commissioner Page** Test is at https://fec-prod-proxy.app.cloud.gov/about/leadership-and-structure/commissioner-page-test/

Issues noted:

- Same issue with horizontal line
- When published, the test Commissioner was not automatically added to the "All Commissioners" page or to the current Commissioner line-up.  (Given that we automated this last year, felt it worth mentioning.)

**Comment by dorothyyeager** [comment]
**Collection page** Test is at https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/test-collection-page/

Collection pages don't need that many features in the body. It may be confusing to users. They are primarily used as landing pages for the H4CC bullets, kind of like a table of contents.

Issue noted: 

- Padding between images and other elements in body portion is very tight. (Note, though, that this is not normally used on collection pages)

**Comment by dorothyyeager** [comment]
@pkfec @johnnyporkchops - We've completed our preliminary testing except for two pages. Comments noted above, but overall nothing that would be a dealbreaker. 

We think @djgarr should help test the full-width page since he's familiar with using it. When we get back from San Antonio conference next week, we'll work with him on that unless you want to talk to him first before we get back.

The only other page left is the Reports Landing page. I tried testing it, but there's some hard-coding in there somehow that prevented me from publishing or saving the page after I created it.

Let @kathycarothers and me know if you would like us to do anymore testing when we get back.

**Comment by djgarr** [comment]
Tried out the full page template. Was able to save a page with "test" content. When I went to preview, I got this message: 
![image](https://user-images.githubusercontent.com/40633757/75253552-bfad0480-57ac-11ea-8ba3-6f115c2837d0.png)

**Comment by djgarr** [comment]
After a note from Dorothy, I published the page. While publishing resolved the "Bad Request" error, the citations that I entered did not show up. Also the image I tried inserting didn't show up either

![image](https://user-images.githubusercontent.com/40633757/75263438-f6d6e200-57bb-11ea-8be8-b442f74f71bb.png)

**Comment by dorothyyeager** [comment]
Content team is done testing - see comments above for some fixes needed for a few page templates. The front end will need to test the Reports Landing template. @pkfec @johnnyporkchops

**Comment by pkfec** [comment]
@dorothyyeager @kathycarothers @djgarr thank you so much for testing new wagtail interface even with your crazy schedules. For  `Reports Landing template` I  have to check with @johnnyporkchops or @JonellaCulmer who offered to help with testing. 

Looking at the  comments, it appears that there `NO` major deal breakers. Can we still move forward with the upgrade?
cc @johnnyporkchops @dorothyyeager @kathycarothers @djgarr

**Comment by djgarr** [comment]
@pkfec would the upgrade affect the content currently in the full width pages?

**Comment by johnnyporkchops** [comment]
@djgarr , can you point me to the page you published that had issues you mention on your comment above?

**Comment by djgarr** [comment]
@johnnyporkchops  H4CC -> Dates and deadlines -> Dates: 2020 reporting dates and deadlines -> "(Test Page)"

**Comment by johnnyporkchops** [comment]
@David, I am seeing the citations after publishing. MNaybe this was a cacheing issue:
<img width="1097" alt="Screen Shot 2020-02-26 at 2 07 37 PM" src="https://user-images.githubusercontent.com/5572856/75378465-bc477500-58a1-11ea-93aa-b3c7ee40b6c1.png">

**Comment by djgarr** [comment]
@johnnyporkchops it may be a caching issue. I hadn't tried to preview it before entering the legal citations info, but I'm seeing what you're seeing now. Looks good from my end of things

**Comment by johnnyporkchops** [comment]
@dorothyyeager wrote:
> * When published, the test Commissioner was not automatically added to the "All Commissioners" page or to the current Commissioner line-up.  (Given that we automated this last year, felt it worth mentioning.)
@dorothy, aplogies for all the specific logic in determining the rendering of the commissioner pages. We cannot have more that one loisted as chair, also, since you put an  term-expiry date for the test commissioner, they did not show up as a current commissioner. Fixing these solves that issue:
<img width="1033" alt="Screen Shot 2020-02-26 at 2 35 45 PM" src="https://user-images.githubusercontent.com/5572856/75380907-d97e4280-58a5-11ea-96e3-f8f534ff6df1.png">

**Comment by johnnyporkchops** [comment]
@dorothyyeager wrote:
> * In the custom table footnote field, html does not work. There are some footnotes which will use links, so we may want to enable this ability. **This should get fixed if we are going to offer this field**.
@dorothyyeager , lets put in a separate issue to either allow that field to accept html or change its field type to  rich-text field (or html filed). Note for follwup issue: Also could be done at template level like we do for  `additional_ information` field on `meeting_page.html` template. See  snippet below.
```
{% autoescape off %}{{ self.additional_information}}{% endautoescape %}
```

**Comment by johnnyporkchops** [comment]
@dorothyyeager , I haves tested adding a report to the Reports About the FEC Section and seems to work as usual.

**Comment by johnnyporkchops** [comment]
@dorothyyeager , @kathycarothers , @djgarr . I have addresses many of the testing comments, but there are a few (like image/car padding, and snippets) that I think it would be best to pair on to make sure we understand the issue and how to fix.

**Comment by dorothyyeager** [comment]
@johnnyporkchops Let's close the testing issue and we can open up tickets to fix those issues. I can pair on this tomorrow when I'm back from San Antonio. (You may want to pair with @djgarr to open up a ticket if needed for full-width page.)

Closing this ticket since testing is complete and issues to follow up on are noted within.
