### ISSUE TITLE
Test search engines to see how Guidance docs come up

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3645]
### Summary

**What we are after:**
For our Guidance doc MVP, we need to make sure google, Bing etc. can find the guidance docs on their own.

### Related issues

#3644 

### Action steps

- [x] Google the docs on [this list](https://docs.google.com/spreadsheets/d/1e2cYmD0z2lEyHfmmSEEirN62IrsMbsneKoOe0vY36Nw/edit#gid=0)
- [x] Bing the docs on [this list](https://docs.google.com/spreadsheets/d/1e2cYmD0z2lEyHfmmSEEirN62IrsMbsneKoOe0vY36Nw/edit#gid=0)
- [x]  Note any that seem like they could use an upgrade SEO-wise.

### Completion criteria

- [ ]  Documents and pages come up in commercial search engines
- [x] Fix SEO for any that didn't.

**Comment by djgarr** [comment]
@kathycarothers and I used the information in the first column to search on google and chrome. Made notes in the 4th (for google searches) and 5th (for bing searches) columns. Most of the searches didn't seem to have the correct FEC document (or any FEC docs) among the first set of results. Let us know if you have any questions

**Comment by dorothyyeager** [comment]
The results were mixed. Most of the documents do come up in search results so we meet the test of the EO, but the forms especially need some SEO work. We're also going to make sure the other guidance docs (especially Campaign Guides) have their SEO properties filled out. That follow-up work will happen in #3657 and #3658 so we'll tackle it there and we can close this ticket.
