### ISSUE TITLE
AFTER 4/28: Update post-2011 guidance FR notices with properties

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3705]
### Summary

**What we are after:**
_We want to make sure the Federal Register notices that we get from GPO and include in guidance search have their properties properly filled out. Because of the way GPO posted notices post-2011, we'll have to do a little hack on the ones after 2011-02._

### Related issues

#3684 - Deploy guidance page on 4/28 - WAIT to reupload documents until this is done.
#3658 - Example of how to fill out properties
https://github.com/fecgov/fec-cms/pull/3695 - prior PR to use an example of how to update sitemap for PDF

### Action steps

**Notices to be fixed:**
https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2011-11_EO13892.pdf
https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2011-13_EO13892.pdf
https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2013-09_EO13892.pdf
https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2013-14_EO13892.pdf
https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2013-16_EO13892.pdf
https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2016-02_EO13892.pdf
https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2019-10_EO13892.pdf

- [x] For each of the notices in question we need to: 

- Go to https://www.govinfo.gov/app/collection/fr and navigate to the date of the notice. 
- Open the entire FR for that date
- Locate the pages that contain the FEC notice
- Do a "print to PDF" and select the specific pages to "save to PDF"
- Save the new PDF in our shared folder over the old one with the same file name we use in the URL
- Fill out the properties tab
- Upload the new file as a replacement file for the old one.

### Completion criteria

- [x] New notices with filled out properties are uploaded into Wagtail
- [x] Mod date is updated in the PDF sitemap
- [x] Revised sitemap is uploaded to Wagtail

**Comment by kathycarothers** [comment]
The pdfs have all been updated and uploaded into Wagtail. They are ready for the next step - the sitemap update.

**Comment by kathycarothers** [comment]
Sent PR for site map.
