### ISSUE TITLE
Disclaimer page follow-up

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3753]
### Summary

**What we are after:**
_Now that we have a nice new disclaimer page, we will want to ensure we're sticking to our one home for content principle and linking the disclaimer page and examples where they fit best on other pages._

### Related issues

- #3724 Publication of disclaimer resource page

### Completion criteria

- [x] Disclaimer page is the main resource for the disclaimer rules
- [x] Other pages that contain disclaimer info keep it to a few summary sentences, and a button and/or card linking disclaimer page and examples.

### Action steps
- [x] Review H4CC and citizens pages to locate disclaimer rule references (or good places for them)
- [x] Insert cards/buttons to replace text as needed.

**Comment by djgarr** [comment]
created a list of pages that discuss disclaimers from the website. will be going through to see if they need to be updated/language needs to be altered to point to resource page

**Comment by djgarr** [comment]
Paired with @dorothyyeager to update pages and link to the main Advertising and disclaimer resource page. Requested review by content team

**Comment by djgarr** [comment]
Made edits. Content team and @JonellaCulmer signed off. Published pages. Closing ticket
