### ISSUE TITLE
Deploy new admin fine calculator

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3789]
**What we're after:**
This ticket is a compilation of the steps required to launch the new administrative fine calculator. 

Steps to completion:
- [x] 1. Merge calculator PR (PR: https://github.com/fecgov/fec-cms/pull/3723)
- [x] 2. Deploy PR
- [x] 3. Edit www to add the calculator to a page or pages
- [x] 4. Remove links on www to old transition calculators and replace with links to new calculator (ticket: https://github.com/fecgov/fec-cms/issues/3732)
- [x] 5. Add redirects to transition to forward any direct links to the new calculator (ticket: https://github.com/fecgov/fec-cms/issues/3783)
- [x]  6. Delete the calculator from transition (ticket: https://github.com/fecgov/fec-cms/issues/3843)

**Comment by dorothyyeager** [comment]
Redirects are now in place and working.

**Comment by rfultz** [comment]
Thought I'd let others know/confirm this should be taken care of now cc @JonellaCulmer @dorothyyeager

**Comment by dorothyyeager** [comment]
Thanks @rfultz - Just saw this. Thank you for all your hard work on the calculator and dear to my heart, taking down old things off of transition! Closing ticket since work is complete.
