### ISSUE TITLE
Redirects 12.5

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3827]
### Summary

**What we are after:**
_We want to get off transition and make sure users are using the most recent versions of our site. So we need to redirect a few things._

### Related issues

- #3783 (Admin fine calculators), we'll combine those redirects with these.
- #3843 (Take down ticket)

### Action steps
- [x] transition redirects PR (see spreadsheet in content team folder)
- [x] www redirects PR or Wagtail redirect as needed.
- [x] Test after @patphongs merges in and deploys redirects

### Completion criteria

- [x] Election results pages and files on transition from 1982 through 2020 are redirected to https://www.fec.gov/introduction-campaign-finance/election-and-voting-information/
- [x] The enforcement materials page at https://transition.fec.gov/law/procedural_materials.shtml is redirected to https://www.fec.gov/legal-resources/enforcement/procedural-materials/
- [X] Ticket to take down files off of transition is put in.

### Future work

Front end removes redirected files from transition in #3843

**Comment by dorothyyeager** [comment]
We discovered some additional www redirects that needed updating since they redirected to transition pages rather than fec.gov pages. Those were added to that PR. It's ready for review by @patphongs

**Comment by dorothyyeager** [comment]
The redirects for the enforcement materials page and the election results pages are working. We'll take down those pages in #3843. Closing this ticket since these particular redirects are working well.
