### ISSUE TITLE
Meeting to discuss tracking goals with Google Tag Manager

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3905]
**What we're after:** We need to determine what our tracking goals for google tag manager are and what should be tracked. 

**Completion criteria:**
- [ ] Compile goals for google tag manager, specifically what we're tracking and what we hope to learn from those areas.
- [ ] Based on goals, determine places/areas of the site to track and add to GTM
- [ ] Open a followup ticket to add tags to identified places on the site (follow up to item 2)

**Comment by JonellaCulmer** [comment]
Preliminary content-related ideas to consider as part of this discussion: 
- Content sync doc
- H4CC 
- Updates sections (Record, Press, Tips)
- Disclaimer example pages
- Guidance search (related ticket: 3744)
- Commissioner pages
- OIG page
- Pages on transition

Other areas: 
- Most popular/used filters (esp sched a, contrib receipts), 
- Filter combinations, some way to detect long-query filter combos…?) 
- User paths like h4cc > guides > PDFs? 
- Links 
   - Where are they going and for how long
   - How does where they're going change over time (in relation to election days)? 
- User path through data
- Wagtail pages
- Should we think about adding GTM to transition, etc or leave them with current GA?

**Comment by JonellaCulmer** [comment]
**Google Tag Manager goals:**
- Create simple reports with 2-3 data points for senior leadership, explanations about why each data point is important
- Better identify user paths through the site, while excluding any and all PII.

**Proposed tags:**
- Contact information clicks (add ID to contact information links)
- Datatable filter usage (specific combinations and individual frequency of use)
- Download attempts for guides, forms and all other PDFs
- Cards (bottom of wagtail pages and reporting examples pages with multiple cards)
- Breadcrumbs
- Side-navigation
- Menu 'all' pages 
- Visualization searches, which excluding any and all PII
- Search box usage (typed searches and clicks)

**Separate work required for reporting updates:**
- Create reports for senior leadership/division heads
- Identify and build stories around the data
- Reporting examples
- Top data pages
- Filter out corporate IPs
- Dates and deadlines
- Public records pages
- Electronic filing pages
- Landing pages

cc: @rfultz

**Comment by JonellaCulmer** [comment]
Closing in favor of next steps:

- https://github.com/fecgov/fec-cms/issues/3160 Tag Manager implementation
- https://github.com/fecgov/fec-cms/issues/3906 Test to make sure that GTM is successfully going into pages, adding GA accounts to pages
- https://github.com/fecgov/fec-cms/issues/3948 Add events into Google Tag Manager
