### ISSUE TITLE
Review analytics after 3 months of GTM event tracking

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4031]
**What we're after:**
Follow-up after the implementation of GTM to document what has been learned and identify any knowledge gaps. 

**Action items:**
- [ ] Compile "report" of GTM event analytics
- [ ] Identify knowledge gaps
- [ ] Make new tool recommendations to close those gaps

**Completion criteria:**
- [ ] Knowledge gaps are identified, list of new tool recommendations
- [ ] Open up followup ticket for procurement, if necessary

**Comment by JonellaCulmer** [comment]
No longer relevant.
