### ISSUE TITLE
Part 2: Migration of Press materials - teaching Press how to upload pdfs and redirects 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4123]
### Summary

**What we're after:**
Since Press is getting Windows 10 laptops soon, they won't be able to use Contribute to update their pages on transition. They have decided to turn some of their pages into pdfs. We need to teach them how to upload these documents and we need to put in the redirects. 

### Related issues

_List any relevant related issue(s)_

- #4067 

### Completion criteria

-[ ] Press needs to specify where on their page they would like to place the pdfs

The pdfs will replace these transition pages:

- [x]  https://transition.fec.gov/press/bkgnd/presidential_fund.shtml

- [x] https://transition.fec.gov/press/bkgnd/AllPublicFunds.xls (This will be an excel file that will be uploaded into the CMS and replaced each time a new update occurs) 

- [x] https://transition.fec.gov/press/bkgnd/EnforcementStatistics.shtml

- [x]  Press learns how to upload and replace their files 

- [x]  Redirects and links are updated 

### Action steps 

- [x] Press Office finalizes the three files 
- [x] Schedule a tutoring session to teach Press how to upload and replacement files 
- [x] Update related links https://www.fec.gov/legal-resources/enforcement/enforcement-profile/, https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/presidential-elections/public-funding-presidential-elections/ (Report section) 
- [x] Redirects are put in 

### Future work

Takedown the Press directory after redirects go in.

**Comment by kathycarothers** [comment]
I have reached out to Press to schedule the meeting. I'm waiting to hear back.
