### ISSUE TITLE
[10/26/20- AFTER DEPLOY] Summary tables deploy checklist

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#4132]
### Summary

**What we're after:**
Once release is deployed on 10/26/20, here are items to complete to publish the `Summary data tables`.

- [x] Set `conditional_js` in each page's settings tab to `statistical_summary.js`, and publish drafts (Pages listed below)
- [x] Publish the landing page (https://fec-prod-proxy.app.cloud.gov/admin/pages/11049/edit/)
- [x] Redirect from the old historical statistics link in browse data to the new one. We changed the name in the URL: https://www.fec.gov/data/browse-data/?tab=statistics PR:#4018
- [ ] Test in browsers (We can use suggested tests in this PRs, how-to-test section https://github.com/fecgov/fec-cms/pull/4088) **IE Note**: There may be an intermittent issue in IE related to the `array.from` polyfill seemingly not working itermittently. Might need @rfultz's expertise to help resolve. Can we just switch to `[].slice.call` technique?

Here are the edit-page links to the pages on prod:
https://fec-prod-proxy.app.cloud.gov/admin/pages/11086/edit/
https://fec-prod-proxy.app.cloud.gov/admin/pages/11085/edit/
https://fec-prod-proxy.app.cloud.gov/admin/pages/11084/edit/
https://fec-prod-proxy.app.cloud.gov/admin/pages/11083/edit/
https://fec-prod-proxy.app.cloud.gov/admin/pages/11082/edit/

### Related Issues/PRs
Issues:
https://github.com/fecgov/fec-cms/issues/4131
https://github.com/fecgov/fec-cms/issues/3958
https://github.com/fecgov/fec-cms/issues/3943

PRs:
https://github.com/fecgov/fec-cms/pull/4088
#4134 

### Future work:
Move PDFs and EXCEL files from transition to prod S3
   https://github.com/fecgov/fec-cms/issues/4052

Migrate archived data summary tables to Wagtail
https://github.com/fecgov/fec-cms/issues/4020

Archive and removal from transiotion
   https://github.com/fecgov/fec-cms/issues/4130
   https://github.com/fecgov/fec-cms/issues/4129

**Comment by kathycarothers** [comment]
@johnnyporkchops do want to comment on the last item in the checklist for this ticket regarding the IE testing? Not sure if that one can be checked off or not. Thanks!

**Comment by johnnyporkchops** [comment]
@kathycarothers , I will test that IE issue now

**Comment by kathycarothers** [comment]
@johnnyporkchops Sounds good. When you finish up can you close the ticket and let me know. I am trying to keep track of all these tickets.

**Comment by kathycarothers** [comment]
@johnnyporkchops is this one okay to close or are you still testing in IE?
