### ISSUE TITLE
Post-migration court case QA for missing data

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4206]
### Summary

**What we are after:**
_We want to finish up QA and ensure we captured any showstoppers or trends._

### Related issues

_List any relevant related issue(s)_

#4165 - QA for migration
#4203 - Clean up for selected / ongoing cases

### Completion criteria

- [x] All QA testers finish checking the pages they were assigned in #4165 for missing data only (to see the transition content, go to https://transition.fec.gov/law/litigation_CCA_Alpha.shtml and find the cases you need on there).
- [x] Any pages with missing data are added to #4205 
- [x] If you spot a Record article with a .shtml link - please comment in #4207 

### Future work

_We'll fix this in #4205_

**Comment by kathycarothers** [comment]
I have completed my assigned parts of the alpha A, B and D

**Comment by prstoetzer** [comment]
E,F,G,and H are checked. No missing information was found, just broken links and a couple of formatting errors detailed in the spreadsheet.

**Comment by JonellaCulmer** [comment]
I-L pages have all be checked. Only two pages were found to have Record articles with .shtml links. They are documented on the team's QA spreadsheet under my name.

**Comment by dorothyyeager** [comment]
Closing. We've done the QA and now comes the clean-up which we've chunked in different tickets.

Clean-up tickets in order of priority:
Important and current cases: #4203 - in progress
Missing data: #4205 13.9
Record links: #4202 and #4207 (this should be wrapped up by 13.8 end)
The rest of the cases: #4204 13.9
Missing cases: #4214 13.9
