### ISSUE TITLE
Research expanding content in H4CC page on creating a political party

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4312]
### Summary

**What we're after:**
_As a citizen who wants to start a new party, I need to understand all the steps._

Informal feedback from Information Division specialists is that the page at https://www.fec.gov/help-candidates-and-committees/registering-political-party/qualifying-political-party/ is not meeting user needs. We need to look at expanding the content on this page to incorporate all of the content in the print version of the Party Guide, including the information that must be included for a committee to register, covered at https://www.fec.gov/help-candidates-and-committees/registering-political-party/ along with information not on that page but in various advisory opinions.

### Related Issues
- [ ] #4385 
- [ ] #4479 
- [ ] #4480
- [ ] #4481

### Action steps
- [x] Review content on both pages vs. the printed Guide and consider flow, completeness, links to other H4CC and election information pages (for example, the ballot access page should be linked)

### Completion criteria
- [x] Recommendation made to Content about next steps
- [x] Implementation ticket has been created (#4729)

### Future steps
- [ ] Draft recommended improvements, noting sources of approved language
- [ ] Circulation to OGC and Info management/Content team
- [ ] Once approved, make changes to pages as needed.

**Comment by patphongs** [comment]
Not enough bandwidth in 14.5, moving to 14.6

**Comment by djgarr** [comment]
Sent to content team to review on 6/28. Created implementation ticket
