### ISSUE TITLE
[DUE 4/15/2021] Testing Wagtail v2.11.6 and Django v3.1 upgrades 

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4529]
# Summary
Wagtail v2.11.6 and Django v3.1 will be deployed to the [feature environment](https://fec-feature-cms.app.cloud.gov/) for testing. Testing ticket to put the new versions of Wagtail and Django through their paces.

## Notes
The related [ticket](https://github.com/fecgov/fec-cms/issues/4384) and [PR](https://github.com/fecgov/fec-cms/pull/4518)

## Details
We're upgrading Wagtail by several versions and Django by a major + minor version and there were some breaking changes.

### Wagtail login and Cookie testing
**Do _not_ clear cookies before starting this test.**

- Login to feature space prior to upgrade.
- Login to feature after upgrade is deployed, make sure login is still successful. Load any page (if there's a cookie error, it will happen immediately. For localhost it's an ugly warning page about `Incorrect padding` but it should be silent for you or ask you to log in again.)

#### How to check cookies (not needed, but if you want to)
One of the breaking changes has to do with how the system encodes and decodes session IDs so we want to make sure we start with cookies from older log-ins. (If you hadn't already had a cookie from the older version, there's no way to fake it without deploying the older (current) version again.) FTR, to check your cookie:
  - go to any page on feature
  - right-click anywhere and choose Inspect
  - go to the Application tab
  - on the left column, choose https://fec-feature-cms.app.cloud.gov under Storage and Cookies
  - in the main area, we're looking for a name of `sessionid`

### Check all templates working (Jonella, coordinating template reviews)
   - [x] About landing page (Pat) - Looks good
   - [x] Alert for emergency use only (Dorothy) - [works great](https://github.com/fecgov/fec-cms/issues/4529#issuecomment-814365622)
   - [x] Collection page (Pat) - Only issue with this page is any of the custom RTE tools (glossary, san serif, and anchors are not working). Same as the issue noted [here](https://github.com/fecgov/fec-cms/issues/4529#issuecomment-814415690).
   - [x] Commissioner page (Kathy) - see comment below. Problem with the glossary option and other options 
   - [x] Contact page (Pat) - Looks good
   - [x] Custom page (Dorothy) - This page template has numerous issues logged in this [comment](https://github.com/fecgov/fec-cms/issues/4529#issuecomment-814415690). Many were in the rich text editor paragraph block functions - @kathycarothers @djgarr please be sure to test those thoroughly on the pages you test. For example, bullets aren't working.
   - [x] Digest page (Kathy) - problems listed below
   - [x] Document feed page (Pat) - Looks good, was able to add additional items to the feed when a document page item was created
   - [x] Document page (Pat) - Looks good, was able to add a new document item that showed up in the feeds and also edit other document pages and have them reflect correctly in the feed.
   - [x] Example page (David) - did not work properly. see comments below
   - [x] Full width page (David) - did not work properly. see comments below
   - [x] Home page (Pat) - Looks good, was able to edit, save, and publish the top features HTML block section
   - [x] Home page banner announcement (Dorothy) - [works great](https://github.com/fecgov/fec-cms/issues/4529#issuecomment-814365622)
   - [x] Legal resources landing page (Pat) - Looks good
   - [x] Meeting page (Paul S) - Works fine
   - [x] OIG landing page (Kathy) - works great (I was able to recreate the page in feature and with no problems.) 
   - [x] Press landing page (Pat)
   - [x] Press release page (Dorothy) - [works well](https://github.com/fecgov/fec-cms/issues/4529#issuecomment-816063823)
   - [x] Record page (Paul S) - Works fine, including a webinar article using tables
   - [x] Reports landing page (Pat) - Looks good, I could make edits to the feed landing page and publish the changes
   - [x] Resource page (Jonella)
   - [x] Services landing page (Pat) - Looks good, was able to edit, save, and publish the page to make change to the top heading block
   - [x] Tips for treasurers page (Paul S) - Works fine

 ### Check visual appearance of a few templates (homepage + a few others)
This is because of the change from `classname` to `form_classname`
- [x] lists on the **homepage** (Jonella + Pat)
    - Homepage looks good, list items appearing in grid as expected (checked by Pat)
- [x] **Custom** pages (Jonella + Custom reviewer)
   - [ ] headings
   - [ ] body headings
   - [ ] sidebar headings
     - Bulleted lists not appearing (checked by Jonella)
- [x] heading for **OIG** Landing Page (Jonella + OIG reviewer)
   - Cannot view OIG landing page (checked by Jonella)
- [x] **Press** Landing Page (Jonella + Press reviewer)
   - [ ] hero
   - [ ] release intro
   - [ ] digest intro
   - [ ] contact info
     - All looks good to me (checked by Jonella)
- [x] hero for **About** landing page (Jonella + Pat)
    - Hero on About landing page looks good (checked by Pat)
- [x] body heading for **Collection** Pages (Jonella + Collection reviewer)
    - All looks good to me (checked by Jonella)
- [x] hero for **Services** landing page (Jonella + Pat)
    - H4CC landing looks good, hero section text can be edited and published in Wagtail as expected. (checked by Pat)

### Check pages outside of Wagtail (Jonella)
- [x] Data pages
- [x] Legal pages
- [x] Calendar page

### Check functionality of Wagtail in general (everyone, while checking other templates)
- [x] Create page
- [x] Edit page
- [x] Preview page
   - No issues with any of these tasks (checked by Jonella)

### Check responsive object (John)
  - Wagtail changed a class for `responsive-object` but I'm not sure where that might be used. Does that sound familiar?

**Have fun breaking things! (always better to break in feature than have problems with Prod)**

### Any cool new Wagtail functionality from upgrade?
- [ ] Rich text editor upgrades? 
- [ ] Does anything in these upgrades help with #4258 (column widths)?

**Comment by patphongs** [comment]
Cool new stuff I just found. I haven't had a chance to play around with it yet though.

- Wagtail reports
- Wagtail page moderation
- Wagtail page lock

<img width="390" alt="Screen Shot 2021-04-01 at 4 49 10 PM" src="https://user-images.githubusercontent.com/12799132/113352458-47e3ce80-930a-11eb-89d8-d4de48d52bfd.png">
<img width="371" alt="Screen Shot 2021-04-01 at 4 48 58 PM" src="https://user-images.githubusercontent.com/12799132/113352603-7d88b780-930a-11eb-9d05-ea7b961422d6.png">

**Comment by rfultz** [comment]
Yep!

Here are the various release notes if you're interested:
[Release notes for Wagtail 2.8](https://docs.wagtail.io/en/stable/releases/2.8.html)
[Release notes for Wagtail 2.9](https://docs.wagtail.io/en/stable/releases/2.9.html)
[Release notes for Wagtail 2.10](https://docs.wagtail.io/en/stable/releases/2.10.html)
[Release notes for Wagtail 2.11](https://docs.wagtail.io/en/stable/releases/2.11.html)

[Release notes for Django 3.0](https://docs.djangoproject.com/en/3.1/releases/3.0/)
[Release notes for Django 3.1](https://docs.djangoproject.com/en/3.1/releases/3.1/)

**Comment by patphongs** [comment]
We've decided to push the upgrade to the 14.4 release which will be on 4/27/2021. This will give us more time to test and deploy after the April quarterly filings are due.

**Comment by dorothyyeager** [comment]
Checks of the home page banner and emergency alert banner went well. Banners appeared when they were supposed to, appeared correctly, and disappeared when they were supposed to. Here's screencaps of each.

<img width="714" alt="banner-test-ok" src="https://user-images.githubusercontent.com/24437369/113764188-a208d900-96e8-11eb-854c-6d490634a242.PNG">
<img width="708" alt="emergency-banner-test" src="https://user-images.githubusercontent.com/24437369/113764192-a2a16f80-96e8-11eb-8406-02eab9af6def.PNG">

**Comment by djgarr** [comment]
Ran into some shenanigans when testing the full width page template 

![image](https://user-images.githubusercontent.com/40633757/113765411-36277000-96ea-11eb-86aa-9192f45538be.png)

**Comment by djgarr** [comment]
The example page didn't work. not sure if there's an issue uploading an image, but I tried and got this result

![image](https://user-images.githubusercontent.com/40633757/113765836-c796e200-96ea-11eb-99dd-9bba13004cd0.png)

**Comment by patphongs** [comment]
Wagtail icon that appears on the page when you're logged in and want to edit the page seems to have disappeared from the circle. The icon is definitely there, but the classes look missing: `wagtail-icon wagtail-icon-wagtail`.

<img width="702" alt="Screen Shot 2021-04-06 at 4 01 44 PM" src="https://user-images.githubusercontent.com/12799132/113771568-87872d80-96f1-11eb-9fdf-968aa348f034.png">

<img width="1340" alt="Screen Shot 2021-04-06 at 3 58 34 PM" src="https://user-images.githubusercontent.com/12799132/113771341-3bd48400-96f1-11eb-90a4-e46f64ca9e62.png">

**Comment by patphongs** [comment]
Page revisions, now called "history" are missing. I tried the "History" button to look at the About landing page history and I don't see any history at all. I should see at least a dozen revisions for the About page.

<img width="470" alt="Screen Shot 2021-04-06 at 4 09 30 PM" src="https://user-images.githubusercontent.com/12799132/113772466-bbaf1e00-96f2-11eb-93d8-909e20a01b87.png">

**Comment by dorothyyeager** [comment]
Custom page template issues

Numbering lists in the rich text editor do not work. Numbers don't render and the numbering when indented didn't change from 1, 2, 3.

![image](https://user-images.githubusercontent.com/24437369/113773898-94595080-96f4-11eb-851d-28d04adbc1bb.png)

Creating an anchor link in the rich text editor paragraph block caused the page to crash and lose unsaved work.

**Comment by patphongs** [comment]
Not a bug but just noting that there is a difference in the page status display in the newer Wagtail version. 

A page is in draft and not published live: It will display the time saved of the latest draft.

<img width="1100" alt="Screen Shot 2021-04-06 at 4 19 15 PM" src="https://user-images.githubusercontent.com/12799132/113773450-09785600-96f4-11eb-96b8-9dd1512fda26.png">

A page is published and live: It will display the time the page was published live and the "Live" button on the right hand side of the template.

<img width="1085" alt="Screen Shot 2021-04-06 at 4 19 35 PM" src="https://user-images.githubusercontent.com/12799132/113773781-768beb80-96f4-11eb-8a41-f1eb89c80b0d.png">

A page is published and has a saved draft that is not published: It will display the time of the last saved draft but also indicate that the page is live.

<img width="1076" alt="Screen Shot 2021-04-06 at 4 21 29 PM" src="https://user-images.githubusercontent.com/12799132/113773887-91f6f680-96f4-11eb-8815-a357c5825588.png">

**Comment by djgarr** [comment]
On the Example page, the numbering and bullet points do not work

![image](https://user-images.githubusercontent.com/40633757/113870225-9ae0da00-977f-11eb-9194-02c35e77f2c9.png)

**Comment by kathycarothers** [comment]
When testing the Commissioner page template I went into the paragraph box to add text. For one of the words I tired to link it to a glossary term and the page crashed. See picture below:

![image](https://user-images.githubusercontent.com/32739251/113878094-4b9ea780-9787-11eb-91f1-0d32866a6acd.png)

**Comment by kathycarothers** [comment]
Digest pages problems:

- The horizontal line is not showing up (should show up above www.fec.gov) see picture below
- Crashed - Glossary terms, san serif font, and anchors 
- Tables and buttons all worked 
- System worked very slowly to enter select and enter the authors 

Crash picture:

![image](https://user-images.githubusercontent.com/32739251/113883069-d386b080-978b-11eb-9853-4e0815cbbcbb.png)

Missing horizontal line:

![image](https://user-images.githubusercontent.com/32739251/113883189-ef8a5200-978b-11eb-8d5a-019fe8413356.png)

**Comment by patphongs** [comment]
No issues with Wagtail login in feature space after logging in on the old version and then logging in on the new version.

**Comment by dorothyyeager** [comment]
**Press Release page template:** [](https://fec-feature-cms.app.cloud.gov/updates/test-press-release-page-4-2021/)

No notable issues. I did not fully test the rich text paragraph editor since issues with that were noted in the custom page template comment. I did notice the bullets worked in this template.

**Comment by rfultz** [comment]
I've created an initial MoSCoW tracker here. Trying to keep things organized and sortable but still conversational shouldn't be such a challenge
https://docs.google.com/spreadsheets/d/17z1ks8BHjFVUls-nVf5a8JaE-HFCvOXBZVE2aJ0eikU/edit?usp=sharing

**Comment by JonellaCulmer** [comment]
**Resource page:**
- Unable to add an image in the rich text editor, no matter how it's formatted: Full, left or right
- Numbered and bulleted lists are working in wagtail editor, but not displaying properly on the page.
- Can't open a PDF linked on the page - get 404.
- Can't open PDFs in document list.
- Images don't show up on feature - but I think that's to be expected, yes?

**Comment by JonellaCulmer** [comment]
**Custom page addition:**
- Checked previously published page and unordered bulleted list is impacted.

**Appearance on .gov:**
<img width="581" alt="Screen Shot 2021-04-12 at 8 53 57 AM" src="https://user-images.githubusercontent.com/31663028/114397603-dbb86480-9b6c-11eb-8a49-a3bf46349391.png">

**Appearance on feature:**
<img width="591" alt="Screen Shot 2021-04-12 at 8 54 05 AM" src="https://user-images.githubusercontent.com/31663028/114397634-e1ae4580-9b6c-11eb-8da1-1eb54fa789ec.png">

**Comment by rfultz** [comment]
> The example page didn't work. not sure if there's an issue uploading an image, but I tried and got this result
> 
> ![image](https://user-images.githubusercontent.com/40633757/113765836-c796e200-96ea-11eb-99dd-9bba13004cd0.png)

David, how's this?
![image](https://user-images.githubusercontent.com/26720877/114611456-1276a380-9c6f-11eb-9ae7-681db26648e8.png)

**Comment by rfultz** [comment]
> Ran into some shenanigans when testing the full width page template
> 
> ![image](https://user-images.githubusercontent.com/40633757/113765411-36277000-96ea-11eb-86aa-9192f45538be.png)
> 
> The table i created showed up correctly below the above image
> 
> Update: ran into the same issues as others when trying to use the glossary function
> 
> ![image](https://user-images.githubusercontent.com/40633757/113908257-51ef4c80-97a4-11eb-8747-b779feaab9d1.png)

@djgarr is this still an issue if we add a `</table>`?

**Comment by rfultz** [comment]
> **Custom page template issues** - test page is at https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/test-of-custom-page-4-2021/ (https://fec-feature-cms.app.cloud.gov/admin/pages/11622/edit/)
> 
> **1. Lists**
> 
> Numbering lists in the rich text editor do not work. Numbers don't render and the numbering when indented didn't change from 1, 2, 3.
> 
> ![image](https://user-images.githubusercontent.com/24437369/113773898-94595080-96f4-11eb-851d-28d04adbc1bb.png)
> 
> **Addition from Pat for unordered lists**
> The bullets do not appear for unordered lists on the custom page and text font size is smaller. [Example link.](https://fec-feature-cms.app.cloud.gov/help-candidates-and-committees/get-tax-id-and-bank-account/)
> 
> <img alt="Screen Shot 2021-04-06 at 4 49 25 PM" width="647" src="https://user-images.githubusercontent.com/12799132/113776708-3169b880-96f8-11eb-9f2b-ee8da7f0db1a.png">
> 
> **2. Links:**
> 
> * **Anchor link:** Creating an anchor link in the rich text editor paragraph block caused the page to crash and lose unsaved work.
>   ![image](https://user-images.githubusercontent.com/24437369/113867524-a979c200-977c-11eb-80a5-11b5665769a7.png)
> * **Glossary link:** Trying to add one caused the content to crash and lose unsaved work.
>   ![image](https://user-images.githubusercontent.com/24437369/113867709-e04fd800-977c-11eb-905d-bba57b57ac81.png)
> 
> **3: Images**
> 
> * Thumbnail images inserted into a page's paragraph block work.
> * The image block - used for larger or medium sized images on a page (like webinar ads) did not render as a separate block.
> * We'd also want to ensure our current padding is still intact on image blocks. For example, an html block added right as an image block should've had some padding between the html and the image, but instead it didn't put the padding there, it looks like it padded in the middle of the html:
> 
> ![image](https://user-images.githubusercontent.com/24437369/113776767-3f1f3e00-96f8-11eb-88dd-111c5f395f52.png)
> 
> **4. Snippets:** There's no padding around the snippet when inserted. (This is needed)
> 
> **5. Superscript:** Trying to apply superscript to text caused the content to crash.
> ![image](https://user-images.githubusercontent.com/24437369/113867884-0ecdb300-977d-11eb-9b6f-10e7b2f147ac.png)
> 
> **6. Sidebar** We only need paragraph and heading.
> 
> **7. Related Topics** - Box size doesn't look correct and words should be centered. Box should be below the Citations box.
> ![image](https://user-images.githubusercontent.com/24437369/113868333-90bddc00-977d-11eb-88d3-1acc22336d3b.png)

@dorothyyeager do these look right now?
![image](https://user-images.githubusercontent.com/26720877/114612754-85cce500-9c70-11eb-9e48-475f719a3d44.png)

**Comment by rfultz** [comment]
@kathycarothers can you point me to where there's an `<hr>` that works? I'm not seeing it on the live site, either.

**Comment by rfultz** [comment]
> * Numbered and bulleted lists are working in wagtail editor

@JonellaCulmer I think these have been fixed now. ?

**Comment by djgarr** [comment]
> > Ran into some shenanigans when testing the full width page template
> > ![image](https://user-images.githubusercontent.com/40633757/113765411-36277000-96ea-11eb-86aa-9192f45538be.png)
> > The table i created showed up correctly below the above image
> > Update: ran into the same issues as others when trying to use the glossary function
> > ![image](https://user-images.githubusercontent.com/40633757/113908257-51ef4c80-97a4-11eb-8747-b779feaab9d1.png)
> 
> @djgarr is this still an issue if we add a `</table>`?

That seems to do the trick. No shenanigans then, just user error. Thanks!

**Comment by patphongs** [comment]
Testing is complete, all issues have been resolved. Merged to develop and will do additional testing.
