### ISSUE TITLE
Create new matching fund submission pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4594]
### Summary

**What we're after:**
We are migrating the matching fund submission files currently found on these pages:
https://transition.fec.gov/finance/disclosure/presidential_matching_fund_submissions_2004_present.shtml
Individual election year pages:
https://transition.fec.gov/finance/disclosure/2016MatchingFundSubmissions.shtml
https://transition.fec.gov/finance/2012matching/2012matching.shtml
https://transition.fec.gov/finance/2008matching/2008matching.shtml
https://transition.fec.gov/finance/disclosure/2004MatchingFundSubmissions.shtml

### Related issues

_List any relevant related issue(s)_

- #4593 Uploading and redirecting related files
- #3386 Design 
- #4541 Language drafting

### Action items
- [x] Create draft pages in the Campaign finance data section to replace these pages using Custom page template, approved language (Dorothy can supply), and [Jonella's mockup](https://github.com/fecgov/fec-cms/issues/3386#issuecomment-815849646)
- [x] Second pair of eyes by content team member and Jonella before publishing
- [x] Link to new landing page is added to hard-coded page at https://www.fec.gov/data/browse-data/?tab=candidates right above the buttons for the presidential map (requires PR)
- [x] Link to new landing page is added to https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/presidential-elections/public-funding-presidential-elections/#reports-and-resources (to replace the transition link in the 5th bullet)
- [x] ZIP files already in S3 bucket are linked.
- [x] Redirects for transition pages are put in place; spreadsheet updated

### Completion criteria

- [x] New pages are published to replace these pages
- [x] Audit/Public Records/Press are informed that the pages are live
- [x] Link on hard-coded data page is put into place and tested - include this test in the redirect ticket #4760)
- [x] Redirects are put in for the old pages and testing ticket is created -Close ticket #4725 once redirects in place. 
- [x]  Do we need to do this ticket to remove exclusion in transition S3 sync for 2020 matching funds yet? :
script https://github.com/fecgov/fec-cms/issues/3385

### Future work

Testing redirects and adding www redirects as needed in Wagtail or www.

**Comment by JonellaCulmer** [comment]
@dorothyyeager @AmyKort I have one concern about placing the new matching fund landing page link on the [browse candidate page](https://www.fec.gov/data/browse-data/?tab=candidates) (in campaign finance data section). The link that's there presently seems to be a much more comprehensive and complete location for matching fund submission information. Candidates who have applied for and candidates who have applied and receive funds can both be found there. 

The new link, which is just for candidates who have applied for but not received public funding seems to be less valuable as a stand-alone link. Also, it's my understanding that we are not likely to create a new matching fund submission page. So each year we go without submissions to add to this page, the less valuable it becomes. I'm just not convinced it rises to the level of importance as the other information surrounding it. 

I'm advocating we keep the other options that were discussed but not the new standalone link on the browse candidates page.

**Comment by kathycarothers** [comment]
@dorothyyeager @JonellaCulmer I have a question regarding the zip files for the 2008 page and the simple document list. The simple document won't allow you to do an external link. The zip files are located in the S3 bucket and not in Wagtail.  So, the simple document list will not work. Was wondering how you wanted to solve this problem - I can create a document list from scratch, however, this page will look a little different from the other pages. Let me know.

**Comment by dorothyyeager** [comment]
@kathycarothers - Let's go ahead and do that and send around in draft mode so @JonellaCulmer can look at it.

**Comment by kathycarothers** [comment]
Email sent out for a second pair of eyes.

**Comment by kathycarothers** [comment]
@dorothyyeager @JonellaCulmer Wanted to follow up on the last bullet point under Completion criteria. Not sure what needs to be done with that one?

**Comment by dorothyyeager** [comment]
@kathycarothers I don't think we need to do anything - now that the files are migrated, and we didn't need a 2020 page. Basically there was something in the transition file that @johnnyporkchops would have needed to remove in order for the 2020 transition page to have worked?

**Comment by kathycarothers** [comment]
@dorothyyeager on that note from your response I am going to close out this ticket. Thank you!
