### ISSUE TITLE
After May 25: Test 14.6 redirects after merge

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4600]
### Summary

**What we're after:**
We're testing redirected pages that were merged into the 14.6 release

### Related issues

- #4485 - Joint fundraising redirects
- #https://github.com/fecgov/fec-proxy/pull/263 - Press Office file AllPublicFunds

### Completion criteria

- [x] Redirects tested and working
- [x] Any needed www redirects (for #4485 there shouldn't be) are submitted or put into Wagtail.
- [x] Any needed take-down ticket is created (for #4485 there shouldn't be a need)
- [x] Take down ticket: #4663

**Comment by djgarr** [comment]
Ticket done
