### ISSUE TITLE
Transition inventory meeting 15.3

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4618]
### Summary

In #4380 , #4381, #4469, we held meetings and made a plan for a lot of transition folders. There's still a lot more to go through! So we need another meeting.

Redirect spreadsheet - see tab marked "Transition Inventory"

### Related issues
#4512 Transition inventory meeting 14.6
#4469 Hold a meeting to go through the transition inventory 14.3 
#4381 Hold a meeting to go through the transition inventory 14.1 
#4380 Take down transition directories
#3755 Get pages/brochures off transition - make a plan
#4762 15.4 Redirects

### Completion criteria

- [x] Meeting is held with content and front end to go over the inventory list picking up with the jpg folder
- [x] Spreadsheet updated to reflect meeting
- [x] Redirect ticket created (#4762)
- [x] Take down ticket created (#4761)
- [x] Testing ticket (#4760 (thanks @kathycarothers))

### Future work

Will need to test redirects and put them in take down ticket too.

**Comment by kathycarothers** [comment]
The next meeting should be scheduled for 15.5

**Comment by djgarr** [comment]
Meeting happened. Tickets created and noted. Closing ticket
