### ISSUE TITLE
QA Wagtail V4 and log any issues

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5545]
### Summary

**What we're after:**
We need to do quality assurance testing and log any issues for the new version of Wagtail V4. It will be deployed to [feature space](https://fec-feature-cms.app.cloud.gov/admin/) for testing.

Take a quick tour of Wagtail 4 (about 7 minute video): https://youtu.be/Js8dIRxwSRY

### QA list
**Overall dashboard styles**
- [x] High contrast colors for better accessibility
- [x] Customized dashboard color palette to match FEC website primary colors. 
- [ ] ~Added environment name to the title and FEC seal to the nav menu bar~
- [x] Collapse the main Wagtail menu tray
- [x] Breadcrumbs at the top expand and collapse when moving mouse on and away from text

**Within page editing dashboard styles**
- [x] Visually shows links to other pages (new icons shown in text)
- [x] Condense pages by collapsing sections
- [x] Plus signs to add blocks have been moved to the left side. Coupled with defining dotted lines to help see nesting of sections.

**Performance and functionality**
- [x] Action buttons moved to the top of the page
- [x] See what type of page template you’re using with the page status tool
- [x] Active preview as you make modifications to the page. Includes multiple formats for mobile and desktop views.
- [x] Ability to duplicate blocks
- [x] Split blocks for content insertion. Ex: split content into separate blocks within the editor such as paragraph, button, table
- [x] Add links by highlighting text and pasting link
- [x] Resource page templates have “Aside” options, similar to footnotes

**Fixed bugs**
- [x] Page title updates in the menu without needing to publish - Seems to affect pages with setting tab (custom, resource, collection, etc.)
- [x] Page position doesn’t bounce around when adding information in table or html blocks
- [x] No delays when working on large HTML blocks (i.e. Alphabetical index)

**CMS Templates**
- [x] About landing page
- [x] Alert for emergency use only
- [x] Collection page
- [x] Commissioner page
- [x] Contact page
- [x] Custom page
- [x] Digest page
- [x] Document feed page
- [x] Document page - [comment](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1404103443)
- [x] Example page - [comment](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1404119755)
- [x] Full width page
- [x] Home page
- [x] Home page banner announcement
- [x] Legal resources landing page
- [x] Meeting page
- [x] Oig landing page
- [x] Press landing page
- [x] Press release page
- [x] Record page
- [x] Reports landing page
- [x] Resource page - [comment](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1403961585) - Also test audit pages to see if it works ok and the user guide may need to be updated.
- [x] Services landing page - not working, will need testing after issues resolved. [Comment](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1403943306)
- [x] Tips for treasurers page - [comment](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1403690370)
- [x] Snippets - [comment](https://github.com/fecgov/fec-cms/issues/5545#issuecomment-1403679484)

### Related issues

_List any relevant related issue(s)_

- #5544 

### Completion criteria

- [ ] Wagtail v4 has been tested and we have a list of fixes/issues

**Comment by dorothyyeager** [comment]
Snippets work but there is an annoying hop upwards whenever you add something or edit something in them.

**Comment by dorothyyeager** [comment]
Tips for treasurer page template does not load properly when selected from the main menu on the left. This was true in Wagtail 2.0 as well. To get to it, you have to go to root > Updates and then select add child page and pick that one.

Once there, the editor function worked fine. The dashboard at the top doesn't feel as intuitive, so we may need to do a little training for Info staff on Wagtail changes.

**Comment by kathycarothers** [comment]
"Meeting page" the toolbar under Agenda item -- Item text is missing a number of features the line feature, picture, redo, undo, the button with the arrow, and the line with the arrow.

**Comment by kathycarothers** [comment]
Make note that we will need to highlight to our users the following:

- The preview button is no longer next to "Save draft" it is now in the top right-hand corner 
- To expand the toolbar you will need to either hit enter for the "/" feature to appear or enter "/" or "/bullet"

**Comment by kathycarothers** [comment]
This function -  Page title updates in menu without needing to publish - is not working when I tested the custom template.

**Comment by djgarr** [comment]
> This function - Page title updates in menu without needing to publish - is not working when I tested the custom template.

I was having trouble getting this to work too.

**Comment by djgarr** [comment]
I'm also missing the ability to preview the Legal Resources page. It's not showing up as an option

![image](https://user-images.githubusercontent.com/40633757/214621098-027bdabb-1cab-4fdc-b781-104d2ad6fc4c.png)

**Comment by djgarr** [comment]
Banner preview doesn't show changes until banner has been published (same as it's been working)

**Comment by dorothyyeager** [comment]
I am unable to create a service landings page or save a draft of one. Will need more testing after this is resolved.

**Comment by dorothyyeager** [comment]
Resource page: I do not love the changes

The layout to go to the next place to create a new section is not intuitive to find. It's hard to create a new section. It works but it's hard to figure out what to click.
The custom table is difficult to work with when customizing links. 
The font overall is too small and layout with the vertical dash lines is confusing

**Comment by dorothyyeager** [comment]
> I'm also missing the ability to preview the Legal Resources page. It's not showing up as an option
> 
> ![image](https://user-images.githubusercontent.com/40633757/214621098-027bdabb-1cab-4fdc-b781-104d2ad6fc4c.png)
> 
> This has been resolved. Preview ability moved.

Although this indicates that figuring out how to preview a page is not user-friendly.

**Comment by djgarr** [comment]
Still an issue when trying to replace a document on the first try with wagtail adding extra characters to the file name

![image](https://user-images.githubusercontent.com/40633757/214659916-e967f45f-764a-4049-b152-dff7243b77a6.png)

Continues to work as it did displaying the proper file name after a second document replacement

**Comment by kathycarothers** [comment]
I agree with Dorothy's regarding the font overall being small

**Comment by kathycarothers** [comment]
Font size differences:

Feature:
![image](https://user-images.githubusercontent.com/32739251/214889761-ceabf0a4-a475-4d90-a90a-703dabdf4d74.png)


Admin

![image](https://user-images.githubusercontent.com/32739251/214889839-ac6f272d-12c0-444b-8c91-28930a6536a2.png)


I am not sure if this really captures the differences

**Comment by kathycarothers** [comment]
Title publishing issue in the menu button we tested templates with the "setting tab" and this seems to affect the ability to change the Wagtail adm menu title without publishing. The pages we tested were the Resource, Collection, and Custom templates.

**Comment by djgarr** [comment]
Everything looks good with the Alphabetical court case index updates

**Comment by kathycarothers** [comment]
David will finish up the html and resource template "aside" function. Pat is going to finish up testing the rest of the templates along with testing Audits work with the resource template.  We also need to update Audit's user manual with any changes from the upgrade to 4.1.1.

**Comment by djgarr** [comment]
Asides in Resource template are working. Seems similar to the example or quoted text that we used on V2

**Comment by patphongs** [comment]
Finished up the rest of testing and things look good. I'll make another ticket to research the issues found during QA
