### ISSUE TITLE
Add document date range filter

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6515]
### What we're after
We want to add document date range filter capability to the MUR, ADR, AF, and AO search. 

In addition, for archived MURs, we want to let users know that the document date range filter is only filterable for current MURs, not archived MURs using a tooltip.

### Related issues
- https://github.com/fecgov/fec-cms/issues/6478
- https://github.com/fecgov/openFEC/pull/6015

### Completion criteria
- [X] Document date range filter added to **AOs** (Addressed by #6586)
- [X] Document date range filter added to **ADRs** (Addressed by #6586)
- [X] Document date range filter added to **Admin Fines** (Addressed by #6586)
- [X] Document date range filter added to **MURs** (Addressed by #6586)
- [x] Tooltip is added to the document date range filter for MURs with the text "Document date range does not search archived cases" (Addressed by #6588)
- [ ]  Add testing 

### Design: New tooltip and document type filter
![Image](https://github.com/user-attachments/assets/9cc4e067-0dc8-416b-ac47-e0830cdf26e3)
Note: The design will be different for MURs, AFs and ADRs, they do not have a submission button
