### ISSUE TITLE
Set up meeting pages for 2025

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#6596]
### Summary

**What we're after:**
As a user who follows Commission news, I need to know when the Commission is meeting in 2025.
### Related issues

_List any relevant related issue(s)_

- #https://github.com/fecgov/fec-cms/issues/5505

### Action items: 

- [ ] Create the pages in Updates using this format for slugs: month-day-year-open-meeting (for open meetings) and month-day-year-executive-session (for executive sessions)
- [ ] Let calendar editor in Info Div and Commission Secretary know when posted.

### Completion criteria

- [ ] Pages created
- [ ] Info and Commission Secretary notified 

### Helpful resources 

https://github.com/fecgov/fec-cms/issues/4885 (Create Meeting Pages for 2022 once Requested by OCS)
https://github.com/fecgov/fec-cms/issues/5267 (Create Meeting Pages for second half of 2022 once Requested by OCS)
https://docs.google.com/document/d/13TJV9YD7V7GKOfp42nL_sT6qql1KUHgGEZ3W0Hwy6To/edit (How to page)
